In [9]:
#importing csv
import pandas as pd

print("\n=== DATA IMPORTS AND FILTERING FOR CHRISTCHURCH===")
# (1) importing listings_19062026.csv
listings_19_06_2026 = pd.read_csv(r"C:\Users\CFakaosi\Data Wrangling\listings_19062026.csv")
print(listings_19_06_2026.head())
print(f"listings_19062026.csv imported successfully!")

#display listings_19062026.csv columns
print(listings_19_06_2026.columns)

#filter for listings in 'Christchurch City' only
listings_19_06_2026 = listings_19_06_2026[listings_19_06_2026['neighbourhood_group'] == 'Christchurch City']
print(listings_19_06_2026)

#add new column for month and year
listings_19_06_2026['month_year'] = '06-2026'
listings_19_06_2026.to_csv('listings_19_06_2026.csv', index=False)
print(f"New column 'month_year' added successfully!")

#repeating the same steps for the rest of the listings csvs
# (2) importing listings_23052026.csv
import pandas as pd
listings_23_05_2026 = listings_23_05_2026 = pd.read_csv(
    r"C:\Users\CFakaosi\Data Wrangling\listings_23052026.csv"
)
print(listings_23_05_2026.head())

#display listings_23052026.csv columns
print(listings_23_05_2026.columns)

#print column 'neighbourhood_group' values to find name used for Christchurch
print(listings_23_05_2026['neighbourhood_group'].unique())

#filter for listings in 'Christchurch City' only
listings_23_05_2026 = listings_23_05_2026[listings_23_05_2026['neighbourhood_group'] == 'Christchurch City']
print(listings_23_05_2026)

#add new column for month and year
listings_23_05_2026['month_year'] = '05-2026'
listings_23_05_2026.to_csv('listings_23_05_2026.csv', index=False)
print(f"New column 'month_year' added successfully!")

#view new column 'month_year'
print(listings_23_05_2026.month_year)

# (3) importing listings_16042026.csv
import pandas as pd
listings_16_04_2026 = listings_23_05_2026 = pd.read_csv(
    r"C:\Users\CFakaosi\Data Wrangling\listings_16042026.csv"
)
print(listings_16_04_2026.head())

#display listings_16042026.csv columns
print(listings_16_04_2026.columns)

#print column 'neighbourhood_group' values to find name used for Christchurch
print(listings_16_04_2026['neighbourhood_group'].unique())

#filter for listings in 'Christchurch City' only
listings_16_04_2026 = listings_16_04_2026[listings_16_04_2026['neighbourhood_group'] == 'Christchurch City']
print(listings_16_04_2026)

#add new column for month and year
listings_16_04_2026['month_year'] = '04-2026'
listings_16_04_2026.to_csv('listings_16_04_2026.csv', index=False)
print(f"New column 'month_year' added successfully!")

#view new column 'month_year'
print(listings_16_04_2026.month_year)

# (4) importing listings_17032026.csv
import pandas as pd
listings_17_03_2026 = listings_23_05_2026 = pd.read_csv(
    r"C:\Users\CFakaosi\Data Wrangling\listings_17032026.csv"
)
print(listings_17_03_2026.head())

#display listings_17032026.csv columns
print(listings_17_03_2026.columns)

#print column 'neighbourhood_group' values to find name used for Christchurch
print(listings_17_03_2026['neighbourhood_group'].unique())

#filter for listings in 'Christchurch City' only
listings_17_03_2026 = listings_17_03_2026[listings_17_03_2026['neighbourhood_group'] == 'Christchurch City']
print(listings_17_03_2026)

#add new column for month and year
listings_17_03_2026['month_year'] = '03-2026'
listings_17_03_2026.to_csv('listings_17_03_2026.csv', index=False)
print(f"New column 'month_year' added successfully!")

#view new column 'month_year'
print(listings_17_03_2026.month_year)

# (5) importing listings_13022026.csv
import pandas as pd
listings_13_02_2026 = listings_23_05_2026 = pd.read_csv(
    r"C:\Users\CFakaosi\Data Wrangling\listings_13022026.csv"
)
print(listings_13_02_2026.head())

#display listings_13022026.csv columns
print(listings_13_02_2026.columns)

#print column 'neighbourhood_group' values to find name used for Christchurch
print(listings_13_02_2026['neighbourhood_group'].unique())

#filter for listings in 'Christchurch City' only
listings_13_02_2026 = listings_13_02_2026[listings_13_02_2026['neighbourhood_group'] == 'Christchurch City']
print(listings_13_02_2026)

#add new column for month and year
listings_13_02_2026['month_year'] = '02-2026'
listings_13_02_2026.to_csv('listings_13_02_2026.csv', index=False)
print(f"New column 'month_year' added successfully!")

#view new column 'month_year'
print(listings_13_02_2026.month_year)

# (6) importing listings_16012026.csv
import pandas as pd
listings_16_01_2026 = listings_23_05_2026 = pd.read_csv(
    r"C:\Users\CFakaosi\Data Wrangling\listings_16012026.csv"
)
print(listings_16_01_2026.head())

#display listings_16012026.csv columns
print(listings_16_01_2026.columns)

#print column 'neighbourhood_group' values to find name used for Christchurch
print(listings_16_01_2026['neighbourhood_group'].unique())

#filter for listings in 'Christchurch City' only
listings_16_01_2026 = listings_16_01_2026[listings_16_01_2026['neighbourhood_group'] == 'Christchurch City']
print(listings_16_01_2026)

#add new column for month and year
listings_16_01_2026['month_year'] = '01-2026'
listings_16_01_2026.to_csv('listings_16_01_2026.csv', index=False)
print(f"New column 'month_year' added successfully!")

#view new column 'month_year'
print(listings_16_01_2026.month_year)

# (7) importing listings_11122025.csv
import pandas as pd
listings_11_12_2025 = listings_23_05_2026 = pd.read_csv(
    r"C:\Users\CFakaosi\Data Wrangling\listings_11122025.csv"
)
print(listings_11_12_2025.head())

#display listings_11122025.csv columns
print(listings_11_12_2025.columns)

#print column 'neighbourhood_group' values to find name used for Christchurch
print(listings_11_12_2025['neighbourhood_group'].unique())

#filter for listings in 'Christchurch City' only
listings_11_12_2025 = listings_11_12_2025[listings_11_12_2025['neighbourhood_group'] == 'Christchurch City']
print(listings_11_12_2025)

#add new column for month and year
listings_11_12_2025['month_year'] = '12-2025'
listings_11_12_2025.to_csv('listings_11_12_2025.csv', index=False)
print(f"New column 'month_year' added successfully!")

#view new column 'month_year'
print(listings_11_12_2025.month_year)

# (8) importing listings_07112025.csv
import pandas as pd
listings_07_11_2025 = listings_23_05_2026 = pd.read_csv(
    r"C:\Users\CFakaosi\Data Wrangling\listings_07112025.csv"
)
print(listings_07_11_2025.head())

#display listings_07112025.csv columns
print(listings_07_11_2025.columns)

#print column 'neighbourhood_group' values to find name used for Christchurch
print(listings_07_11_2025['neighbourhood_group'].unique())

#filter for listings in 'Christchurch City' only
listings_07_11_2025 = listings_07_11_2025[listings_07_11_2025['neighbourhood_group'] == 'Christchurch City']
print(listings_07_11_2025)

#add new column for month and year
listings_07_11_2025['month_year'] = '11-2025'
listings_07_11_2025.to_csv('listings_07_11_2025.csv', index=False)
print(f"New column 'month_year' added successfully!")

#view new column 'month_year'
print(listings_07_11_2025.month_year)

# (9) importing listings_05102025.csv
import pandas as pd
listings_05_10_2025 = listings_23_05_2026 = pd.read_csv(
    r"C:\Users\CFakaosi\Data Wrangling\listings_05102025.csv"
)
print(listings_05_10_2025.head())

#display listings_05102025.csv columns
print(listings_05_10_2025.columns)

#print column 'neighbourhood_group' values to find name used for Christchurch
print(listings_05_10_2025['neighbourhood_group'].unique())

#filter for listings in 'Christchurch City' only
listings_05_10_2025 = listings_05_10_2025[listings_05_10_2025['neighbourhood_group'] == 'Christchurch City']
print(listings_05_10_2025)

#add new column for month and year
listings_05_10_2025['month_year'] = '10-2025'
listings_05_10_2025.to_csv('listings_05_10_2025.csv', index=False)
print(f"New column 'month_year' added successfully!")

#view new column 'month_year'
print(listings_05_10_2025.month_year)

print("\n=== CONCATENATION PROCESS FOR CHRISTCHURCH===")

#concatenate all prepared csvs into one Christchurch file
import glob

listings_files = ["listings_20_06_2026.csv", 
                  "listings_23_05_2026.csv",
                  "listings_16_04_2026.csv",
                  "listings_17_03_2026.csv",
                  "listings_13_02_2026.csv",
                  "listings_16_01_2026.csv",
                  "listings_11_12_2025.csv",
                  "listings_07_11_2025.csv",
                  "listings_05_10_2025.csv"
                  ]
print("Processing files...")

#df = pd.concat((pd.read_csv(f) for f in listings_files),
               #ignore_index=True)

all_dfs = []

for filename in listings_files:

    parts = filename.replace(".csv", "").split("_")

    day = parts[-3]
    month = parts[-2]
    year = parts[-1]

    month_year = f"{month}_{year}"

    publish_date = pd.to_datetime(
        f"{day}/{month}/{year}",
        format="%d/%m/%Y"
    )

    temp_df = pd.read_csv(filename)

    temp_df["month_year"] = month_year
    temp_df["publish_date"] = publish_date

    all_dfs.append(temp_df)

df = pd.concat(all_dfs, ignore_index=True)

print("\n=== Concatenation process complete and saved into new csv===")

print("Concatenation complete")
print(f"Rows: {len(df)}")

df.to_csv("Christchurch_merged_listings_2025_2026.csv", index=False)


#display results in terminal
print(df.head()) # first 5 rows
print(df.shape) # rows, columns
print("Christchurch listings (2025-2026) merged and saved successfully!")

#produce suitable summary statistics

# (1) displaying numerical summary statistics
print("\n=== NUMERICAL SUMMARY STATISTICS ===")
print(df.describe().T.to_string())

# (2) displaying categorical summary statistics
print("\n=== CATEGORICAL SUMMARY STATISTICS ===")
print(df.describe(include='object').T.to_string())

# (3) displaying number of missing values per column
print("\n=== MISSING VALUES SUMMARY STATISTICS ===")
missing_summary = df.isnull().sum().to_frame(name='missing_values')
print(missing_summary.to_string())

#saving all results in a new excel file 'summary_statistics.txt'
with open("summary_statistics.txt", "w", encoding="utf-8") as f:
 f.write("=== NUMERICAL SUMMARY STATISTICS ===\n")
 f.write(df.describe().T.to_string())

 f.write("\n\n=== CATEGORICAL SUMMARY STATISTICS ===\n")
 f.write(df.describe(include='object').T.to_string())

 f.write("\n\n=== MISSING VALUES SUMMARY ===\n")
 f.write(missing_summary.to_string())

#reproduce workflows and plots from Deliverable 2:

#clean up the csv eg. missing values
df_cleaned = df.dropna(subset=['price'])

print(df_cleaned['price'].dtype)

# (1) plot distribution of price as a histogram for only Christchurch City
#importing necessary libraries
import matplotlib.pyplot as plt
import numpy as np

#plot histogram using the 'price' column
plt.hist(df_cleaned['price'], bins=400, edgecolor='black', color='skyblue')

plt.xlim(0,4500) #defining min and max values to use for graph

plt.title('Price Distribution of Airbnb Listings in Christchurch City') #title
plt.xlabel('Price (NZD)') #x-label
plt.ylabel('Number of Listings') #y-label

#display the histogram
plt.show()
plt.close()


#making sure the last_revies column is a date_time
df["last_review"] = pd.to_datetime(
    df["last_review"],
    format="%Y-%m-%d"
)

print("\n=== DIFFERENCE BETWEEN SCRAPE/PUBLISH DATE AND LAST REVIEW DATE ===")
#calculate the last review date
df["days_since_review"] = (
    df["publish_date"] - df["last_review"]
).dt.days

print(df[["last_review", "publish_date", "days_since_review"]])

print("\n=== NUMBER OF LISTINGS BY PUBLISH DATE ===")
#counting how many records were published on each date
print(df["publish_date"].value_counts())

#
#print(sorted(df["publish_date"].unique()))

#print((df["days_since_review"] < 0).sum())

#print(
    #(df["days_since_review"] < 0).mean() * 100
#)


# (3) find how many properties get the highest numbers of reviews in Christchurch
print("\n=== TOP 10% MOST REVIEWED PROPERTIES IN CHRISTCHURCH ===")

#calculating top 10% threshold
threshold = df_cleaned['number_of_reviews'].quantile(0.90)

#filter for properties that meet or exceed top 10% mark
top_10 = df_cleaned[df_cleaned['number_of_reviews'] >= threshold]

#display top 10% most reviewed properties in CHC
print(f"Number of properties in the top 10%: {threshold} properties")
print(top_10)

# DELIVERABLE 4 - Clean up the airbnb listings
#remove neighbourhood_group, last_review, reviews_per_month, license fields
df_cleaned = df_cleaned.drop(columns=["neighbourhood_group", "last_review", "reviews_per_month", "license"])
print(df_cleaned.columns.tolist())

=== DATA IMPORTS AND FILTERING FOR CHRISTCHURCH===
                    id                                             name  \
0   968224198043666870                                             Room
1             24742386  Garden Studio With Ensuite (Breakfast included)
2  1654821509215926144                       Papanui Oasis Entire House
3              7403587                  Warm Cosy Quiet Home Semi Rural
4             22570965                            One Bedroom Apartment

       host_id       host_name neighbourhood_group  neighbourhood  latitude  \
0  516048910.0            Heer   Christchurch City     Innes Ward -43.49815
1   43654083.0           Kathy   Christchurch City   Papanui Ward -43.50407
2  754856789.0  Jonathan Allan   Christchurch City   Papanui Ward -43.48954
3   38795211.0           Wendy   Christchurch City  Halswell Ward -43.57605
4   44728588.0     Anita Marie   Christchurch City   Papanui Ward -43.48606

   longitude        room_type  price  minimum_nights  number_of_reviews  \
0  172.65054     Private room   64.0             1.0                  0
1  172.59607  Entire home/apt  172.0             1.0                205
2  172.61408  Entire home/apt  230.0             1.0                  5
3  172.54686     Private room  143.0             1.0                  0
4  172.61688       Hotel room  202.0             1.0                  3

  last_review  reviews_per_month  calculated_host_listings_count  \
0         NaN                NaN                             1.0
1  2026-05-19               2.31                             1.0
2  2026-05-16               2.24                             1.0
3         NaN                NaN                             1.0
4  2022-04-27               0.03                             6.0

   availability_365  number_of_reviews_ltm  license month_year
0                89                      0      NaN    06-2026
1               241                     36      NaN    06-2026
2               335                      5      NaN    06-2026
3               263                      0      NaN    06-2026
4               342                      0      NaN    06-2026
listings_19062026.csv imported successfully!
Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood_group',
       'neighbourhood', 'latitude', 'longitude', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'availability_365', 'number_of_reviews_ltm', 'license', 'month_year'],
      dtype='object')
                       id                                              name  \
0      968224198043666870                                              Room
1                24742386   Garden Studio With Ensuite (Breakfast included)
2     1654821509215926144                        Papanui Oasis Entire House
3                 7403587                   Warm Cosy Quiet Home Semi Rural
4                22570965                             One Bedroom Apartment
...                   ...                                               ...
3464   847521223991840944                               City Park Townhouse
3465  1675859538548775874           Relaxing Christchurch Base near the CBD
3466  1701868509562071280  Unique central city standalone home with parking
3467  1361903004430574659                              Home in Central City
3468   993567873481058119      Sumner Beach, 2 blocks to the surf!\nMonthly

           host_id            host_name neighbourhood_group   neighbourhood  \
0     5.160489e+08                 Heer   Christchurch City      Innes Ward
1     4.365408e+07                Kathy   Christchurch City    Papanui Ward
2     7.548568e+08       Jonathan Allan   Christchurch City    Papanui Ward
3     3.879521e+07                Wendy   Christchurch City   Halswell Ward
4     4.472859e+07          Anita Marie   Christchurch City    Papanui Ward
...            ...                  ...                 ...             ...
3464  4.994250e+08                 Casa   Christchurch City    Central Ward
3465  3.317632e+08  Managed By Williams   Christchurch City    Central Ward
3466  1.673594e+18                 Mike   Christchurch City    Central Ward
3467  3.301075e+08               Nathan   Christchurch City    Central Ward
3468  4.359511e+06                Chris   Christchurch City  Heathcote Ward

       latitude   longitude        room_type  price  minimum_nights  \
0    -43.498150  172.650540     Private room   64.0             1.0
1    -43.504070  172.596070  Entire home/apt  172.0             1.0
2    -43.489540  172.614080  Entire home/apt  230.0             1.0
3    -43.576050  172.546860     Private room  143.0             1.0
4    -43.486060  172.616880       Hotel room  202.0             1.0
...         ...         ...              ...    ...             ...
3464 -43.537517  172.625023  Entire home/apt  194.0             1.0
3465 -43.539614  172.634315  Entire home/apt  218.0             1.0
3466 -43.524128  172.642483  Entire home/apt  169.0             3.0
3467 -43.533780  172.642170  Entire home/apt  256.0             1.0
3468 -43.574279  172.765747  Entire home/apt    NaN             7.0

      number_of_reviews last_review  reviews_per_month  \
0                     0         NaN                NaN
1                   205  2026-05-19               2.31
2                     5  2026-05-16               2.24
3                     0         NaN                NaN
4                     3  2022-04-27               0.03
...                 ...         ...                ...
3464                151  2026-04-13               3.80
3465                  1  2026-05-29               1.00
3466                  0         NaN                NaN
3467                 66  2026-05-19               4.21
3468                  3  2024-06-06               0.11

      calculated_host_listings_count  availability_365  number_of_reviews_ltm  \
0                                1.0                89                      0
1                                1.0               241                     36
2                                1.0               335                      5
3                                1.0               263                      0
4                                6.0               342                      0
...                              ...               ...                    ...
3464                             2.0               241                     24
3465                           165.0               341                      1
3466                             2.0               102                      0
3467                             1.0               204                     51
3468                             1.0                 0                      0

      license month_year
0         NaN    06-2026
1         NaN    06-2026
2         NaN    06-2026
3         NaN    06-2026
4         NaN    06-2026
...       ...        ...
3464      NaN    06-2026
3465      NaN    06-2026
3466      NaN    06-2026
3467      NaN    06-2026
3468      NaN    06-2026

[3469 rows x 19 columns]
New column 'month_year' added successfully!
                    id                                               name  \
0  1578850527873087488               Rural Village Life.\nAn Organic Stay
1             46195268                        Hackfalls Arboretum Cottage
2             42644070  Mahaanui Cottage Farmstay Experience, Gisborne NZ
3   643330737845926684   'Takahi Orchard' \nspacious home, pool and views
4   790075688231963515                           Beach Front Little Villa

     host_id    host_name neighbourhood_group      neighbourhood   latitude  \
0   13613955  John Oswald   Gisborne District       Waipaoa Ward -38.518906
1  374078960       Kirsty   Gisborne District       Waipaoa Ward -38.770210
2  161457574        Sally   Gisborne District       Waipaoa Ward -38.732980
3  461502930      Hinemoa   Gisborne District       Waipaoa Ward -38.708965
4  245381749    Tatapouri   Gisborne District  Tawhiti-Uawa Ward -38.646634

    longitude        room_type  price  minimum_nights  number_of_reviews  \
0  177.895309  Entire home/apt  149.0             1.0                  2
1  177.540980  Entire home/apt  163.0             2.0                 43
2  177.586580  Entire home/apt  330.0             1.0                 46
3  177.900051  Entire home/apt  560.0             2.0                 29
4  178.145206  Entire home/apt  228.0             1.0                 34

  last_review  reviews_per_month  calculated_host_listings_count  \
0  2025-12-31               0.41                               1
1  2026-03-28               0.65                               1
2  2025-08-12               0.63                               2
3  2026-01-07               0.70                               1
4  2026-04-27               0.82                               7

   availability_365  number_of_reviews_ltm  license
0               106                      2      NaN
1               353                     10      NaN
2               235                      1      NaN
3               200                      3      NaN
4               322                      8      NaN
Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood_group',
       'neighbourhood', 'latitude', 'longitude', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'availability_365', 'number_of_reviews_ltm', 'license'],
      dtype='object')
['Gisborne District' 'Wairoa District' 'Hastings District'
 'New Plymouth District' 'Westland District' 'Waimakariri District'
 'Porirua City' 'Upper Hutt City' 'Lower Hutt City' 'Wellington City'
 'Kaikoura District' 'Buller District' 'Grey District' 'Christchurch City'
 'Waikato District' 'Matamata-Piako District' 'Stratford District'
 'South Taranaki District' 'Ruapehu District' 'Whanganui District'
 'Rangitikei District' 'Manawatu District' 'Hamilton City'
 'Waipa District' 'Ōtorohanga District' 'Far North District'
 'Whangarei District' 'South Waikato District' 'Ōpōtiki District'
 'Selwyn District' 'Ashburton District' 'Timaru District' 'Dunedin City'
 'Clutha District' 'Thames-Coromandel District' 'Hauraki District'
 'Kaipara District' 'Waitomo District' 'Napier City' 'Taupo District'
 'Western Bay of Plenty District' 'Tauranga City' 'Rotorua District'
 'Whakatane District' 'Kawerau District' 'Kapiti Coast District'
 "Central Hawke's Bay District" 'Palmerston North City' 'Tararua District'
 'Horowhenua District' 'Masterton District' 'Carterton District'
 'South Wairarapa District' 'Tasman District' 'Nelson City'
 'Marlborough District' 'Hurunui District' 'Gore District'
 'Invercargill City' 'Auckland' 'Mackenzie District' 'Waimate District'
 'Chatham Islands Territory' 'Waitaki District' 'Central Otago District'
 'Queenstown-Lakes District' 'Southland District']
                        id                                               name  \
1652   1386687997521702157  Queen bedroom with ensuite.Close to Airport & ...
1653   1431402493983919661                            Sweet home near airport
1654    675113531579372721                                    2 Bedroom House
1655   1686101904773720813                         Harewood Lodge Family Room
1656   1267135241648958968                          The Cottage at Greystones
...                    ...                                                ...
49171   976369154673473011                                      Surfside Bach
49208             35842951    #69 Romantic Waterfront Apt  4-Poster Bed & Spa
49254             52861676             #2 The Wharf Seaview Apartments by AVI
49259  1615152766965283892    Villa Akaroa - Akaroa Pet Friendly Holiday Home
49279  1153098927137918897             #67 La Voyageur Waterfront Apts by AVI

                   host_id                 host_name neighbourhood_group  \
1652             686755100                     Harry   Christchurch City
1653             542186568                    Sharon   Christchurch City
1654              98758734  North South Holiday Park   Christchurch City
1655   1685772148285939721                      Moon   Christchurch City
1656             119195642                    Millie   Christchurch City
...                    ...                       ...                 ...
49171            351305354                     Sarah   Christchurch City
49208             70726871                    Darren   Christchurch City
49254             70726871                    Darren   Christchurch City
49259            145244100                  Bachcare   Christchurch City
49279             70726871                    Darren   Christchurch City

              neighbourhood   latitude   longitude        room_type  price  \
1652          Harewood Ward -43.448611  172.629582     Private room   86.0
1653          Harewood Ward -43.493106  172.582291  Entire home/apt  197.0
1654          Harewood Ward -43.471008  172.570089  Entire home/apt  254.0
1655          Harewood Ward -43.475540  172.525180     Private room  160.0
1656          Harewood Ward -43.501619  172.433375  Entire home/apt  160.0
...                     ...        ...         ...              ...    ...
49171        Heathcote Ward -43.569620  172.773830  Entire home/apt  913.0
49208  Banks Peninsula Ward -43.808630  172.962310       Hotel room  210.0
49254  Banks Peninsula Ward -43.808310  172.961790  Entire home/apt  220.0
49259  Banks Peninsula Ward -43.808272  172.964139  Entire home/apt  651.0
49279  Banks Peninsula Ward -43.810340  172.960570  Entire home/apt  230.0

       minimum_nights  number_of_reviews last_review  reviews_per_month  \
1652              1.0                111  2026-05-09               8.00
1653              1.0                 69  2026-05-10               5.93
1654              1.0                  4  2026-03-01               0.09
1655              1.0                  0         NaN                NaN
1656              1.0                 44  2026-05-03               2.41
...               ...                ...         ...                ...
49171             3.0                 19  2026-02-28               0.65
49208             1.0                128  2026-05-17               1.66
49254             1.0                  3  2025-08-14               0.06
49259             2.0                  0         NaN                NaN
49279             1.0                  2  2024-10-04               0.08

       calculated_host_listings_count  availability_365  \
1652                                1               362
1653                                7               182
1654                               19               315
1655                                5               283
1656                                2               246
...                               ...               ...
49171                               1               105
49208                              22               272
49254                              22               130
49259                            1200               363
49279                              22               213

       number_of_reviews_ltm  license
1652                     100      NaN
1653                      69      NaN
1654                       1      NaN
1655                       0      NaN
1656                      36      NaN
...                      ...      ...
49171                      8      NaN
49208                     27      NaN
49254                      1      NaN
49259                      0      NaN
49279                      0      NaN

[3361 rows x 18 columns]
New column 'month_year' added successfully!
1652     05-2026
1653     05-2026
1654     05-2026
1655     05-2026
1656     05-2026
          ...
49171    05-2026
49208    05-2026
49254    05-2026
49259    05-2026
49279    05-2026
Name: month_year, Length: 3361, dtype: object
      id                                     name  host_id        host_name  \
0  36194                 The Wharf Hub - a voyage   128489            Lloyd
1  46071                                   Kamahi   202747            Donna
2  51362       PORTAGE HEIGHTS MARLBOROUGH SOUNDS   236005  Ralph & Cynthia
3  54257  Bethells Beach Cottage son scenic coast   254289            Trude
4  54680                          By Waipuna Park   256989          Heather

    neighbourhood_group             neighbourhood  latitude  longitude  \
0      Ōpōtiki District     Waioeka-Waiotahi Ward -37.99937  177.28239
1        Taupo District    Turangi-Tongariro Ward -38.90862  175.75285
2  Marlborough District   Marlborough Sounds Ward -41.19326  174.03374
3              Auckland            Waitākere Ward -36.89646  174.45160
4         Tauranga City  Te Papa-Welcome Bay Ward -37.73336  176.17517

         room_type  price  minimum_nights  number_of_reviews last_review  \
0     Private room  150.0             1.0                 12  2017-02-26
1  Entire home/apt  360.0             2.0                 29  2025-04-21
2     Private room  343.0             2.0                 77  2026-04-05
3  Entire home/apt  373.0             2.0                  8  2026-03-06
4     Private room  137.0             1.0                 37  2025-10-25

   reviews_per_month  calculated_host_listings_count  availability_365  \
0               0.07                               1                88
1               0.36                               2               290
2               0.52                               1               177
3               0.50                               3               344
4               0.23                               1               313

   number_of_reviews_ltm  license
0                      0      NaN
1                      0      NaN
2                      4      NaN
3                      5      NaN
4                      3      NaN
Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood_group',
       'neighbourhood', 'latitude', 'longitude', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'availability_365', 'number_of_reviews_ltm', 'license'],
      dtype='object')
['Ōpōtiki District' 'Taupo District' 'Marlborough District' 'Auckland'
 'Tauranga City' 'Kapiti Coast District' 'New Plymouth District'
 'Nelson City' 'Timaru District' 'Dunedin City' 'Waikato District'
 'Hastings District' 'Queenstown-Lakes District' 'Wellington City'
 'Thames-Coromandel District' 'Tasman District' 'Central Otago District'
 'Whangarei District' 'Hurunui District' 'Christchurch City'
 'Palmerston North City' 'Far North District' 'Kaikoura District'
 'Lower Hutt City' 'Gisborne District' 'Waitaki District' 'Porirua City'
 'Ruapehu District' 'Waipa District' 'Hamilton City' 'Napier City'
 'Rotorua District' 'Westland District' 'Southland District'
 'Whakatane District' 'Waimakariri District'
 'Western Bay of Plenty District' 'Masterton District' 'Upper Hutt City'
 'Kaipara District' 'Buller District' 'Gore District' 'Hauraki District'
 'Selwyn District' 'Whanganui District' 'Ashburton District'
 'Mackenzie District' 'Waitomo District' 'Wairoa District'
 'Clutha District' 'Matamata-Piako District' 'South Wairarapa District'
 'Horowhenua District' "Central Hawke's Bay District" 'Grey District'
 'Waimate District' 'Carterton District' 'Invercargill City'
 'Ōtorohanga District' 'South Waikato District' 'Stratford District'
 'Manawatu District' 'South Taranaki District' 'Rangitikei District'
 'Tararua District' 'Chatham Islands Territory' 'Kawerau District']
                        id                                              name  \
32                  319770                       Gateway to the South Island
79                  737452                                   Mumfords Akaroa

C:\Users\CFakaosi\AppData\Local\Temp\ipykernel_32028\532556256.py:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  listings_16_04_2026['month_year'] = '04-2026'

      id                                     name  host_id        host_name  \
0  36194                 The Wharf Hub - a voyage   128489            Lloyd
1  46071                                   Kamahi   202747            Donna
2  51362       PORTAGE HEIGHTS MARLBOROUGH SOUNDS   236005  Ralph & Cynthia
3  54257  Bethells Beach Cottage son scenic coast   254289            Trude
4  54680                          By Waipuna Park   256989          Heather

    neighbourhood_group             neighbourhood  latitude  longitude  \
0      Ōpōtiki District     Waioeka-Waiotahi Ward -37.99937  177.28239
1        Taupo District    Turangi-Tongariro Ward -38.90862  175.75285
2  Marlborough District   Marlborough Sounds Ward -41.19326  174.03374
3              Auckland            Waitākere Ward -36.89646  174.45160
4         Tauranga City  Te Papa-Welcome Bay Ward -37.73336  176.17517

         room_type  price  minimum_nights  number_of_reviews last_review  \
0     Private room  150.0             1.0                 12  2017-02-26
1  Entire home/apt  406.0             2.0                 29  2025-04-21
2     Private room  343.0             2.0                 76  2026-02-15
3  Entire home/apt  373.0             2.0                  8  2026-03-06
4     Private room  137.0             1.0                 37  2025-10-25

   reviews_per_month  calculated_host_listings_count  availability_365  \
0               0.07                               1                88
1               0.36                               2               325
2               0.52                               1               176
3               0.54                               3               350
4               0.23                               1               283

   number_of_reviews_ltm  license
0                      0      NaN
1                      1      NaN
2                      3      NaN
3                      5      NaN
4                      4      NaN
Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood_group',
       'neighbourhood', 'latitude', 'longitude', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'availability_365', 'number_of_reviews_ltm', 'license'],
      dtype='object')
['Ōpōtiki District' 'Taupo District' 'Marlborough District' 'Auckland'
 'Tauranga City' 'Kapiti Coast District' 'New Plymouth District'
 'Nelson City' 'Timaru District' 'Dunedin City' 'Waikato District'
 'Hastings District' 'Queenstown-Lakes District' 'Wellington City'
 'Thames-Coromandel District' 'Tasman District' 'Central Otago District'
 'Whangarei District' 'Hurunui District' 'Christchurch City'
 'Palmerston North City' 'Far North District' 'Kaikoura District'
 'Lower Hutt City' 'Gisborne District' 'Waitaki District' 'Porirua City'
 'Ruapehu District' 'Waipa District' 'Hamilton City' 'Napier City'
 'Rotorua District' 'Westland District' 'Southland District'
 'Whakatane District' 'Waimakariri District'
 'Western Bay of Plenty District' 'Masterton District' 'Upper Hutt City'
 'Buller District' 'Kaipara District' 'Gore District' 'Hauraki District'
 'Selwyn District' 'Whanganui District' 'Ashburton District'
 'Mackenzie District' 'Waitomo District' 'Wairoa District'
 'Clutha District' 'Matamata-Piako District' 'South Wairarapa District'
 'Horowhenua District' "Central Hawke's Bay District" 'Grey District'
 'Waimate District' 'Carterton District' 'Invercargill City'
 'Manawatu District' 'Ōtorohanga District' 'South Waikato District'
 'Stratford District' 'South Taranaki District' 'Rangitikei District'
 'Tararua District' 'Chatham Islands Territory' 'Kawerau District']
                        id                                             name  \
32                  319770                      Gateway to the South Island
79                  737452                                  Mumfords Akaroa
126                1004252                 Governors Bay Waterfront Retreat
135                1007247                                 Clarence Cottage
154                1097487                       Heritage Magic in Merivale
...                    ...                                              ...
49006  1640954935753057131      Luxury Hagley Park Townhouse | Office Setup
49013  1641017802634346207                            New Unit on Wildberry
49019  1641173610760680347   Modern Central City Sanctuary on Welles Street
49039  1641729827665261732              Stylish Manchester Street City Stay
49061  1642261081635583319  Impeccable Style, Exceptional Views! Pool + BBQ

         host_id            host_name neighbourhood_group  \
32       1639584             Jennifer   Christchurch City
79       3851282                Nicky   Christchurch City
126      5523780                Rosie   Christchurch City
135      4765250                 John   Christchurch City
154      4993285             Paulette   Christchurch City
...          ...                  ...                 ...
49006  482671075  Care Property Stays   Christchurch City
49013  698646358     Helena Elizabeth   Christchurch City
49019  202585247                Ohana   Christchurch City
49039  331763232  Managed By Williams   Christchurch City
49061   49642171      Lily-SimplyHost   Christchurch City

              neighbourhood   latitude   longitude        room_type  price  \
32               Innes Ward -43.509610  172.655520     Private room  198.0
79     Banks Peninsula Ward -43.823430  172.946430  Entire home/apt  394.0
126    Banks Peninsula Ward -43.618890  172.653140  Entire home/apt  183.0
135          Riccarton Ward -43.539550  172.606970  Entire home/apt  334.0
154          Fendalton Ward -43.511490  172.625400     Private room  189.0
...                     ...        ...         ...              ...    ...
49006          Central Ward -43.525320  172.628390  Entire home/apt  354.0
49013          Linwood Ward -43.546564  172.668800  Entire home/apt  177.0
49019          Central Ward -43.538833  172.637889  Entire home/apt  290.0
49039          Central Ward -43.530320  172.638920  Entire home/apt  192.0
49061         Cashmere Ward -43.567990  172.648520  Entire home/apt  622.0

       minimum_nights  number_of_reviews last_review  reviews_per_month  \
32                1.0                  3  2015-01-09               0.02
79                2.0                100  2025-12-21               0.67
126               2.0                224  2026-02-28               1.43
135               2.0                119  2026-02-21               0.80
154               1.0                230  2025-03-03               2.07
...               ...                ...         ...                ...
49006             1.0                  0         NaN                NaN
49013             1.0                  0         NaN                NaN
49019             1.0                  0         NaN                NaN
49039             2.0                  0         NaN                NaN
49061             1.0                  0         NaN                NaN

       calculated_host_listings_count  availability_365  \
32                                  1               363
79                                  1               299
126                                 1               169
135                                 1               298
154                                 1               321
...                               ...               ...
49006                             147               263
49013                               1                10
49019                             137                43
49039                             132               342
49061                              95               176

       number_of_reviews_ltm  license
32                         0      NaN
79                         2      NaN
126                        9      NaN
135                        5      NaN
154                        0      NaN
...                      ...      ...
49006                      0      NaN
49013                      0      NaN
49019                      0      NaN
49039                      0      NaN
49061                      0      NaN

[3227 rows x 18 columns]
New column 'month_year' added successfully!
32       03-2026
79       03-2026
126      03-2026
135      03-2026
154      03-2026
          ...
49006    03-2026
49013    03-2026
49019    03-2026
49039    03-2026
49061    03-2026
Name: month_year, Length: 3227, dtype: object

C:\Users\CFakaosi\AppData\Local\Temp\ipykernel_32028\532556256.py:91: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  listings_17_03_2026['month_year'] = '03-2026'

                    id                                             name  \
0  1065244682287350993                                     Totara Ridge
1             43834420  Two Bedroom Access Apartment @ Riverlodge Motel
2   650824893416631133              HOT TUB 4 bdr lake/town 5 min drive
3  1024845988222917943                             Central Bush Retreat
4  1290216239281506940                                  Lakefront Oasis

     host_id          host_name        neighbourhood_group  \
0  120675713            Melanie           Rotorua District
1  342336273  Riverlodge Nelson                Nelson City
2  129957281            Brendan  Queenstown-Lakes District
3   74736891            Carolyn              Grey District
4   43140098             Joanne  Queenstown-Lakes District

              neighbourhood   latitude   longitude        room_type  price  \
0         Area Outside Ward -38.160760  176.301700  Entire home/apt    NaN
1         Area Outside Ward -41.268320  173.287260  Entire home/apt    NaN
2               Wanaka Ward -44.681370  169.157915  Entire home/apt    NaN
3              Central Ward -42.459262  171.207429  Entire home/apt    NaN
4  Queenstown-Wakatipu Ward -45.026562  168.696314  Entire home/apt    NaN

   minimum_nights  number_of_reviews last_review  reviews_per_month  \
0             1.0                141  2026-02-06               5.65
1             1.0                 17  2025-02-26               0.26
2             1.0                305  2026-02-01               6.94
3             1.0                 90  2026-01-29               3.31
4             2.0                 14  2025-12-22               0.96

   calculated_host_listings_count  availability_365  number_of_reviews_ltm  \
0                               1               215                     64
1                              11               264                      1
2                              15                64                     67
3                               2               150                     35
4                               3                 0                      9

   license
0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood_group',
       'neighbourhood', 'latitude', 'longitude', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'availability_365', 'number_of_reviews_ltm', 'license'],
      dtype='object')
['Rotorua District' 'Nelson City' 'Queenstown-Lakes District'
 'Grey District' 'Auckland' 'New Plymouth District' 'Napier City'
 'Southland District' 'Christchurch City' 'Taupo District'
 'Whangarei District' 'Tasman District' 'Western Bay of Plenty District'
 'Hamilton City' 'Thames-Coromandel District' 'Far North District'
 'Hauraki District' 'Tauranga City' 'Westland District' 'Lower Hutt City'
 'Hastings District' 'Horowhenua District' 'Clutha District'
 'Invercargill City' 'Central Otago District' 'Wellington City'
 'Gisborne District' 'Mackenzie District' 'Hurunui District'
 'Whakatane District' 'Dunedin City' 'Upper Hutt City'
 'South Wairarapa District' 'Ruapehu District' 'Selwyn District'
 'Kaikoura District' 'Waitaki District' 'Carterton District'
 'Marlborough District' 'Kaipara District' 'Waikato District'
 'Waipa District' 'Palmerston North City' 'Rangitikei District'
 'Waimate District' 'Ōtorohanga District' 'Whanganui District'
 'Kapiti Coast District' 'Buller District' 'South Taranaki District'
 'Masterton District' 'Porirua City' 'Waimakariri District'
 'Wairoa District' 'Ashburton District' "Central Hawke's Bay District"
 'Gore District' 'Timaru District' 'Chatham Islands Territory'
 'Matamata-Piako District' 'Stratford District' 'South Waikato District'
 'Waitomo District' 'Manawatu District' 'Ōpōtiki District'
 'Tararua District' 'Kawerau District']
                        id                                               name  \
11      948754193074213128                Majestic CourtMotel/No Cleaning Fee
18     1103787467513725189                    Strowan manor - off street park
30                41858980                The Boathouse - Akaroa Holiday Home
45     1096862117472449647          Luxury Brand New 2 Bed 5 Minutes From CBD
48     1534253212713740725                                     Stadium studio
...                    ...                                                ...
48632             40327816  Stylish apartment in historic Edwardian building.
48658   914058317533702896  Haven near Hagley Park, Hospital, Parakiore, Avon
48661  1056862048445629495                 Style meets comfort 2 Bed CHCH CBD
48672  1577133355897972736  New York Loft | Private Car Park | Walk to Sta...
48687  1413412509320106859          Very Central 2BR - Balcony & Full Kitchen

         host_id            host_name neighbourhood_group  \
11     238866720               Deepak   Christchurch City
18       8056856             Samantha   Christchurch City
30     145244100             Bachcare   Christchurch City
45      90918992      Lily-SimplyHost   Christchurch City
48     220001641                   Ed   Christchurch City
...          ...                  ...                 ...
48632  117503447              Liliana   Christchurch City
48658  482671075  Care Property Stays   Christchurch City
48661  551181197  Paula Kat Charlotte   Christchurch City
48672  551181197  Paula Kat Charlotte   Christchurch City
48687  202585247                Ohana   Christchurch City

              neighbourhood   latitude   longitude        room_type  price  \
11           Riccarton Ward -43.530280  172.593970     Private room    NaN
18           Fendalton Ward -43.508191  172.609608  Entire home/apt    NaN
30     Banks Peninsula Ward -43.807200  172.966750  Entire home/apt    NaN
45           Fendalton Ward -43.514130  172.624080  Entire home/apt    NaN
48             Central Ward -43.528969  172.641933     Private room    NaN
...                     ...        ...         ...              ...    ...
48632          Central Ward -43.537490  172.637250  Entire home/apt    NaN
48658          Central Ward -43.537372  172.625301  Entire home/apt    NaN
48661          Central Ward -43.536179  172.635303  Entire home/apt    NaN
48672          Central Ward -43.536490  172.638044  Entire home/apt    NaN
48687          Central Ward -43.535450  172.635391  Entire home/apt    NaN

       minimum_nights  number_of_reviews last_review  reviews_per_month  \
11                1.0                  2  2023-11-18               0.07
18                2.0                 31  2026-02-13               1.30
30                2.0                 21  2025-10-21               0.29
45                1.0                 12  2025-12-25               0.51
48                1.0                  2  2025-11-30               0.67
...               ...                ...         ...                ...
48632             1.0                207  2026-02-14               2.79
48658             1.0                 67  2025-12-22               2.07
48661             1.0                 80  2026-01-30               3.10
48672             1.0                  5  2026-01-31               2.59
48687             1.0                 57  2026-02-08               6.04

       calculated_host_listings_count  availability_365  \
11                                  2               361
18                                  1               122
30                               1470               361
45                                  1               152
48                                  1                83
...                               ...               ...
48632                               2               336
48658                             134               228
48661                             189               232
48672                             189               221
48687                             133               109

       number_of_reviews_ltm  license
11                         0      NaN
18                        20      NaN
30                         1      NaN
45                         2      NaN
48                         2      NaN
...                      ...      ...
48632                     36      NaN
48658                     14      NaN
48661                     45      NaN
48672                      5      NaN
48687                     57      NaN

[3190 rows x 18 columns]
New column 'month_year' added successfully!
11       02-2026
18       02-2026
30       02-2026
45       02-2026
48       02-2026
          ...
48632    02-2026
48658    02-2026
48661    02-2026
48672    02-2026
48687    02-2026
Name: month_year, Length: 3190, dtype: object

C:\Users\CFakaosi\AppData\Local\Temp\ipykernel_32028\532556256.py:116: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  listings_13_02_2026['month_year'] = '02-2026'

                    id                                               name  \
0  1578850527873087488               Rural Village Life.\nAn Organic Stay
1   643330737845926684   'Takahi Orchard' \nspacious home, pool and views
2  1038844996005598345                                    Country Retreat
3             42644070  Mahaanui Cottage Farmstay Experience, Gisborne NZ
4  1590274405473687805                                    Country Retreat

     host_id        host_name neighbourhood_group neighbourhood   latitude  \
0   13613955      John Oswald   Gisborne District  Waipaoa Ward -38.518906
1  461502930          Hinemoa   Gisborne District  Waipaoa Ward -38.708965
2   41393381           Andrew   Gisborne District  Waipaoa Ward -38.610624
3  161457574            Sally   Gisborne District  Waipaoa Ward -38.732980
4  201913567  ABC Partnership   Gisborne District  Waipaoa Ward -38.611180

    longitude        room_type  price  minimum_nights  number_of_reviews  \
0  177.895309  Entire home/apt    NaN             1.0                  2
1  177.900051  Entire home/apt    NaN             2.0                 29
2  177.878852  Entire home/apt    NaN             1.0                  6
3  177.586580  Entire home/apt    NaN             1.0                 46
4  177.878310  Entire home/apt    NaN             1.0                  0

  last_review  reviews_per_month  calculated_host_listings_count  \
0  2025-12-31               2.00                               1
1  2026-01-07               0.78                               1
2  2025-04-26               0.24                               2
3  2025-08-12               0.67                               2
4         NaN                NaN                               1

   availability_365  number_of_reviews_ltm  license
0               365                      2      NaN
1               256                      4      NaN
2                73                      1      NaN
3               351                      1      NaN
4                82                      0      NaN
Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood_group',
       'neighbourhood', 'latitude', 'longitude', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'availability_365', 'number_of_reviews_ltm', 'license'],
      dtype='object')
['Gisborne District' 'Wairoa District' 'Hastings District'
 'New Plymouth District' 'Westland District' 'Waimakariri District'
 'Porirua City' 'Upper Hutt City' 'Lower Hutt City' 'Wellington City'
 'Kaikoura District' 'Buller District' 'Grey District' 'Christchurch City'
 'Waikato District' 'Matamata-Piako District' 'Stratford District'
 'South Taranaki District' 'Ruapehu District' 'Whanganui District'
 'Rangitikei District' 'Manawatu District' 'Hamilton City'
 'Waipa District' 'Ōtorohanga District' 'Far North District'
 'Whangarei District' 'South Waikato District' 'Ōpōtiki District'
 'Selwyn District' 'Ashburton District' 'Timaru District' 'Dunedin City'
 'Clutha District' 'Thames-Coromandel District' 'Hauraki District'
 'Kaipara District' 'Waitomo District' 'Napier City' 'Taupo District'
 'Western Bay of Plenty District' 'Tauranga City' 'Rotorua District'
 'Whakatane District' 'Kawerau District' 'Kapiti Coast District'
 "Central Hawke's Bay District" 'Palmerston North City' 'Tararua District'
 'Horowhenua District' 'Masterton District' 'Carterton District'
 'South Wairarapa District' 'Tasman District' 'Nelson City'
 'Marlborough District' 'Hurunui District' 'Gore District'
 'Invercargill City' 'Auckland' 'Mackenzie District' 'Waimate District'
 'Chatham Islands Territory' 'Waitaki District' 'Central Otago District'
 'Queenstown-Lakes District' 'Southland District']
                        id                                      name  \
1659              39559012                    Self Contained Unit 25
1660   1395109904560781257              Cozy guesthouse in casebrook
1661   1219952962339024701  4 Bedroom Home near Christchurch Airport
1662    675113531579372721                           2 Bedroom House
1663   1431402493983919661                   Sweet home near airport
...                    ...                                       ...
46614             43406592                   Halfmoon Cottage Akaroa
46630  1243103804158737990             Bruce Waterfront Apartment 31
46646             52861676    #2 The Wharf Seaview Apartments by AVI
46678             49019590                       Gem of a Kiwi Bach!
46725   997983300304872339     Charming Waterfront Retreat Redcliffs

         host_id                           host_name neighbourhood_group  \
1659    98758734            North South Holiday Park   Christchurch City
1660   433251428                               Donna   Christchurch City
1661   250552000                              Sreela   Christchurch City
1662    98758734            North South Holiday Park   Christchurch City
1663   542186568                              Sharon   Christchurch City
...          ...                                 ...                 ...
46614   93365561                         Cor & Margo   Christchurch City
46630   24205506  Mayie, Judi And Karen At Bookahome   Christchurch City
46646   70726871                              Darren   Christchurch City
46678   57015466                               Laura   Christchurch City
46725   81390838                       Perfect Stays   Christchurch City

              neighbourhood   latitude   longitude        room_type  price  \
1659          Harewood Ward -43.471040  172.569870     Private room    NaN
1660          Harewood Ward -43.478480  172.602470  Entire home/apt    NaN
1661          Harewood Ward -43.451390  172.618190  Entire home/apt    NaN
1662          Harewood Ward -43.471008  172.570089  Entire home/apt    NaN
1663          Harewood Ward -43.493106  172.582291  Entire home/apt    NaN
...                     ...        ...         ...              ...    ...
46614  Banks Peninsula Ward -43.760060  172.914500     Private room    NaN
46630  Banks Peninsula Ward -43.808277  172.960096  Entire home/apt    NaN
46646  Banks Peninsula Ward -43.808310  172.961790  Entire home/apt    NaN
46678        Heathcote Ward -43.581370  172.776070  Entire home/apt    NaN
46725        Heathcote Ward -43.558030  172.739230  Entire home/apt    NaN

       minimum_nights  number_of_reviews last_review  reviews_per_month  \
1659              1.0                  1  2020-10-06               0.02
1660              1.0                  3  2025-08-16               0.32
1661              2.0                  7  2025-07-09               0.55
1662              1.0                  3  2024-02-11               0.07
1663              1.0                 47  2026-01-16               6.24
...               ...                ...         ...                ...
46614             1.0                  0         NaN                NaN
46630             2.0                 16  2025-12-17               1.06
46646             1.0                  3  2025-08-14               0.07
46678             2.0                154  2025-12-26               2.71
46725             2.0                  4  2024-07-15               0.15

       calculated_host_listings_count  availability_365  \
1659                               19               270
1660                                1               267
1661                                2               164
1662                               19               326
1663                                9                92
...                               ...               ...
46614                               4                74
46630                              79               123
46646                              23               223
46678                               1                68
46725                              44               208

       number_of_reviews_ltm  license
1659                       0      NaN
1660                       3      NaN
1661                       2      NaN
1662                       0      NaN
1663                      47      NaN
...                      ...      ...
46614                      0      NaN
46630                     12      NaN
46646                      1      NaN
46678                     26      NaN
46725                      0      NaN

[3057 rows x 18 columns]
New column 'month_year' added successfully!
1659     01-2026
1660     01-2026
1661     01-2026
1662     01-2026
1663     01-2026
          ...
46614    01-2026
46630    01-2026
46646    01-2026
46678    01-2026
46725    01-2026
Name: month_year, Length: 3057, dtype: object

C:\Users\CFakaosi\AppData\Local\Temp\ipykernel_32028\532556256.py:141: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  listings_16_01_2026['month_year'] = '01-2026'

                    id                                               name  \
0  1324266711925923792                      Room 3 The Old Patearoa Hotel
1             26276648     The Parklet. Charming spacious country cottage
2             39034006  Il Piccolo. The Little One. Luxurious and Tran...
3  1060567563159282460                        Audax Estate Private Room A
4             50384982  Pīwakawaka Lodge - a place for rest and advent...

     host_id host_name           neighbourhood_group           neighbourhood  \
0  378829837     Lewis        Central Otago District          Maniototo Ward
1  166479899      Debs  Central Hawke's Bay District   Aramoana-Ruahine Ward
2   42932175    Alison          Marlborough District     Wairau-Awatere Ward
3  139051714    Shanel                 Tauranga City  Otumoetai-Pyes Pa Ward
4   26136368   Stephen                Taupo District  Turangi-Tongariro Ward

   latitude  longitude        room_type  price  minimum_nights  \
0 -45.27223  170.05313     Private room    NaN               1
1 -39.92629  176.66901  Entire home/apt    NaN               1
2 -41.55515  173.89767  Entire home/apt    NaN               1
3 -37.75128  176.11434     Private room    NaN               1
4 -39.00053  175.81220  Entire home/apt    NaN               2

   number_of_reviews last_review  reviews_per_month  \
0                  0         NaN                NaN
1                 63  2025-01-16               0.70
2                 75  2025-12-01               1.02
3                  0         NaN                NaN
4                 73  2025-11-21               1.37

   calculated_host_listings_count  availability_365  number_of_reviews_ltm  \
0                               3               364                      0
1                               1               328                      1
2                               1               178                     14
3                               2               269                      0
4                               2               314                      8

   license
0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood_group',
       'neighbourhood', 'latitude', 'longitude', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'availability_365', 'number_of_reviews_ltm', 'license'],
      dtype='object')
['Central Otago District' "Central Hawke's Bay District"
 'Marlborough District' 'Tauranga City' 'Taupo District'
 'Palmerston North City' 'Christchurch City' 'Hamilton City' 'Nelson City'
 'Dunedin City' 'Kaipara District' 'Auckland' 'Masterton District'
 'Waikato District' 'Thames-Coromandel District' 'Gisborne District'
 'Whanganui District' 'Kapiti Coast District' 'Waipa District'
 'Whangarei District' 'Tasman District' 'Horowhenua District'
 'Manawatu District' 'Far North District' 'Rotorua District'
 'Mackenzie District' 'New Plymouth District' 'South Wairarapa District'
 'Queenstown-Lakes District' 'Hurunui District' 'Wellington City'
 'Selwyn District' 'Lower Hutt City' 'Hastings District' 'Porirua City'
 'Napier City' 'Western Bay of Plenty District' 'Hauraki District'
 'Ruapehu District' 'Southland District' 'Westland District'
 'Ashburton District' 'Grey District' 'Upper Hutt City'
 'Kaikoura District' 'Buller District' 'Wairoa District' 'Clutha District'
 'Whakatane District' 'South Waikato District' 'Gore District'
 'Waitaki District' 'Carterton District' 'Matamata-Piako District'
 'Invercargill City' 'Rangitikei District' 'Ōtorohanga District'
 'Timaru District' 'Waimate District' 'South Taranaki District'
 'Ōpōtiki District' 'Waitomo District' 'Stratford District'
 'Chatham Islands Territory' 'Tararua District' 'Waimakariri District'
 'Kawerau District']
                        id                                             name  \
7      1272718399011169311  Grand Hotel & Bar Akaroa - Triple Room En-suite
28     1200338218728704148                                    Black Diamond
35     1337349703674320075                                 Room with a View
40                50706253                                  The Sumner Loft
42      952384856334481871                                             Cool
...                    ...                                              ...
49755             10973248            Rivendell Cottage in Christchurch CBD
49770  1360304618422114506       Sunny Studio Haven in Central Christchurch
49775             18725148              Happy house with cat/ dog housemate
49825  1012866483314569831  Unwind in Stylish New Accom in Bustling CHCH U3
49830  1225844540208606760                 Cosy Central Addington 3bed Home

         host_id          host_name neighbourhood_group         neighbourhood  \
7      599729683                Ben   Christchurch City  Banks Peninsula Ward
28      91121378              Holly   Christchurch City  Banks Peninsula Ward
35      32636421              Karyn   Christchurch City         Cashmere Ward
40      84622864  Matt And Caroline   Christchurch City        Heathcote Ward
42     530346508              Rajni   Christchurch City        Riccarton Ward
...          ...                ...                 ...                   ...
49755   56932783       Pamela Marie   Christchurch City          Central Ward
49770  331763232   Benjamin Dearden   Christchurch City          Central Ward
49775  115396571             Stuart   Christchurch City          Papanui Ward
49825   74811135             Yaoyao   Christchurch City          Central Ward
49830   69908412              Alica   Christchurch City         Spreydon Ward

        latitude   longitude        room_type  price  minimum_nights  \
7     -43.799554  172.969986     Private room    NaN               1
28    -43.631885  172.725165  Entire home/apt    NaN               1
35    -43.566430  172.648140     Private room    NaN               1
40    -43.568590  172.758740  Entire home/apt    NaN               2
42    -43.537612  172.584131     Private room    NaN               1
...          ...         ...              ...    ...             ...
49755 -43.527100  172.647390     Private room    NaN               2
49770 -43.537843  172.631978  Entire home/apt    NaN               2
49775 -43.471300  172.626450     Private room    NaN               3
49825 -43.529380  172.655280  Entire home/apt    NaN               1
49830 -43.542720  172.614100  Entire home/apt    NaN               2

       number_of_reviews last_review  reviews_per_month  \
7                      1  2025-06-01               0.15
28                   126  2025-12-09               8.31
35                     2  2025-02-22               0.20
40                   170  2025-11-15               3.35
42                     0         NaN                NaN
...                  ...         ...                ...
49755                110  2025-12-05               1.31
49770                 10  2025-10-30               1.06
49775                  3  2023-12-22               0.04
49825                 34  2025-10-26               1.34
49830                 33  2025-10-05               2.28

       calculated_host_listings_count  availability_365  \
7                                   6               300
28                                  1               262
35                                  2               363
40                                  1               311
42                                  1               269
...                               ...               ...
49755                               1               102
49770                             116               116
49775                               1               178
49825                              43                 0
49830                               1                 0

       number_of_reviews_ltm  license
7                          1      NaN
28                       108      NaN
35                         2      NaN
40                        36      NaN
42                         0      NaN
...                      ...      ...
49755                     18      NaN
49770                     10      NaN
49775                      0      NaN
49825                     16      NaN
49830                     27      NaN

[3180 rows x 18 columns]
New column 'month_year' added successfully!
7        12-2025
28       12-2025
35       12-2025
40       12-2025
42       12-2025
          ...
49755    12-2025
49770    12-2025
49775    12-2025
49825    12-2025
49830    12-2025
Name: month_year, Length: 3180, dtype: object

C:\Users\CFakaosi\AppData\Local\Temp\ipykernel_32028\532556256.py:166: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  listings_11_12_2025['month_year'] = '12-2025'

                   id                                          name  \
0  624738836054092532  Adorable one bedroom guesthouse in Matawhero
1            27634049                           Manutuke Guesthouse
2            46646702   3 Bedroom Rural Retreat 4 minutes to Rhythm
3  901683946888702590   Large Gisborne Home set among the vineyards
4            31147594                                Makaraka Magic

     host_id            host_name neighbourhood_group           neighbourhood  \
0  273636348  Lynn Margaret Innes   Gisborne District  Taruheru-Patutahi Ward
1    5899851                Libby   Gisborne District  Taruheru-Patutahi Ward
2   96756672              Kalinda   Gisborne District  Taruheru-Patutahi Ward
3  255254541                Grace   Gisborne District  Taruheru-Patutahi Ward
4   79514293     Lisa And Geordie   Gisborne District  Taruheru-Patutahi Ward

   latitude  longitude        room_type   price  minimum_nights  \
0 -38.65246  177.92307     Private room   140.0               2
1 -38.67679  177.90885  Entire home/apt   300.0               2
2 -38.57596  177.92913  Entire home/apt  1500.0               3
3 -38.55062  177.92467  Entire home/apt  1000.0               4
4 -38.65198  177.95693  Entire home/apt   221.0               2

   number_of_reviews last_review  reviews_per_month  \
0                 24  2025-05-23               0.60
1                 12  2024-01-28               0.15
2                  2  2024-12-31               0.03
3                  1  2023-12-31               0.04
4                 46  2025-10-27               0.55

   calculated_host_listings_count  availability_365  number_of_reviews_ltm  \
0                              15               165                      2
1                               1               348                      0
2                               1               359                      1
3                               1               351                      0
4                               1               104                      2

   license
0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood_group',
       'neighbourhood', 'latitude', 'longitude', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'availability_365', 'number_of_reviews_ltm', 'license'],
      dtype='object')
['Gisborne District' 'Wairoa District' 'Hastings District'
 'New Plymouth District' 'Westland District' 'Waimakariri District'
 'Upper Hutt City' 'Lower Hutt City' 'Porirua City' 'Wellington City'
 'Kaikoura District' 'Buller District' 'Grey District' 'Christchurch City'
 'Waikato District' 'Matamata-Piako District' 'Stratford District'
 'South Taranaki District' 'Ruapehu District' 'Whanganui District'
 'Manawatu District' 'Hamilton City' 'Rangitikei District'
 'Waipa District' 'Ōtorohanga District' 'Far North District'
 'Whangarei District' 'Ōpōtiki District' 'South Waikato District'
 'Selwyn District' 'Ashburton District' 'Timaru District' 'Dunedin City'
 'Clutha District' 'Thames-Coromandel District' 'Hauraki District'
 'Kaipara District' 'Waitomo District' 'Napier City' 'Taupo District'
 'Western Bay of Plenty District' 'Tauranga City' 'Rotorua District'
 'Whakatane District' 'Kawerau District' 'Kapiti Coast District'
 "Central Hawke's Bay District" 'Palmerston North City' 'Tararua District'
 'Horowhenua District' 'Masterton District' 'Carterton District'
 'South Wairarapa District' 'Tasman District' 'Nelson City'
 'Marlborough District' 'Hurunui District' 'Gore District'
 'Invercargill City' 'Auckland' 'Mackenzie District' 'Waimate District'
 'Chatham Islands Territory' 'Waitaki District' 'Central Otago District'
 'Queenstown-Lakes District' 'Southland District']
                        id                                             name  \
3368   1345090284419926150    Quiet Peaceful Rest in Casebrook near Airport
3369    757992042127459324                     Private room in Christchurch
3370   1408467299578818634       Guesthouse on Gardiners - No cleaning fee.
3371              40206974                                 The School House
3372              47771758         Up to 7, handy location, spacious living
...                    ...                                              ...
48484  1289499394296943880                            Akaroa Oceanview Home
48486             45639036       #72 3 Bedroom Apt with partial Water Views
48493             35842951  #69 Romantic Waterfront Apt  4-Poster Bed & Spa
48496   976369154673473011                                Seaside Surf Bach
48540             43499389                              Beachside Apartment

         host_id                 host_name neighbourhood_group  \
3368   432570678                     Faith   Christchurch City
3369   120365151                       Don   Christchurch City
3370   300616410                 Elisabeth   Christchurch City
3371    98758734  North South Holiday Park   Christchurch City
3372    66848108                   Timothy   Christchurch City
...          ...                       ...                 ...
48484   81390838                     Katie   Christchurch City
48486   70726871                    Darren   Christchurch City
48493   70726871                    Darren   Christchurch City
48496  351305354                     Sarah   Christchurch City
48540    9427994                      Mary   Christchurch City

              neighbourhood   latitude   longitude        room_type  price  \
3368          Harewood Ward -43.478500  172.602490     Private room  200.0
3369          Harewood Ward -43.482980  172.586260     Private room   56.0
3370          Harewood Ward -43.462400  172.588730  Entire home/apt  108.0
3371          Harewood Ward -43.470290  172.570930  Entire home/apt  377.0
3372          Harewood Ward -43.489050  172.592720  Entire home/apt  127.0
...                     ...        ...         ...              ...    ...
48484  Banks Peninsula Ward -43.813318  172.955258  Entire home/apt  237.0
48486  Banks Peninsula Ward -43.808670  172.961200  Entire home/apt  203.0
48493  Banks Peninsula Ward -43.808630  172.962310       Hotel room    NaN
48496        Heathcote Ward -43.569620  172.773830  Entire home/apt    NaN
48540  Banks Peninsula Ward -43.814970  172.951350     Private room  248.0

       minimum_nights  number_of_reviews last_review  reviews_per_month  \
3368                1                  0         NaN                NaN
3369                1                  5  2023-04-20               0.15
3370                1                 99  2025-11-11              15.31
3371                2                  1  2022-06-26               0.02
3372                2                 93  2025-11-06               1.63
...               ...                ...         ...                ...
48484               2                 19  2025-10-25               1.60
48486               1                 58  2025-10-11               0.95
48493               1                114  2025-10-13               1.61
48496               3                 11  2025-01-28               0.48
48540               1                  4  2023-03-02               0.08

       calculated_host_listings_count  availability_365  \
3368                                1                90
3369                                1               362
3370                                1                69
3371                               19               324
3372                                3                24
...                               ...               ...
48484                              46               285
48486                              23               231
48493                              23               269
48496                               1                29
48540                               2               269

       number_of_reviews_ltm  license
3368                       0      NaN
3369                       0      NaN
3370                      99      NaN
3371                       0      NaN
3372                      25      NaN
...                      ...      ...
48484                     19      NaN
48486                     15      NaN
48493                     20      NaN
48496                      5      NaN
48540                      0      NaN

[3047 rows x 18 columns]
New column 'month_year' added successfully!
3368     11-2025
3369     11-2025
3370     11-2025
3371     11-2025
3372     11-2025
          ...
48484    11-2025
48486    11-2025
48493    11-2025
48496    11-2025
48540    11-2025
Name: month_year, Length: 3047, dtype: object

C:\Users\CFakaosi\AppData\Local\Temp\ipykernel_32028\532556256.py:191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  listings_07_11_2025['month_year'] = '11-2025'

                    id                              name    host_id  \
0  1301058524473641980                        Lake house  664639500
1  1074933484046268258                      Rata Retreat  177030298
2  1075015563519391913                   Luxmore Heights  558111144
3  1046705564556087439  2 Bedrooms with Scenic Park View  462120635
4             40183765          Ensuite Cabin (Sleeps 6)   98758734

                  host_name        neighbourhood_group  \
0                      John  Queenstown-Lakes District
1                    Twizel         Mackenzie District
2                    Raewyn         Southland District
3                    Prince                   Auckland
4  North South Holiday Park          Christchurch City

              neighbourhood   latitude   longitude        room_type  price  \
0  Queenstown-Wakatipu Ward -45.030103  168.712810  Entire home/apt  900.0
1               Pukaki Ward -44.258180  170.088128  Entire home/apt  233.0
2       Mararoa Waimea Ward -45.419780  167.728810  Entire home/apt  138.0
3  Maungakiekie-Tāmaki Ward -36.898185  174.840678  Entire home/apt  187.0
4             Harewood Ward -43.470020  172.570880     Private room    NaN

   minimum_nights  number_of_reviews last_review  reviews_per_month  \
0               7                  0         NaN                NaN
1               1                  8  2025-02-24               0.40
2               2                 33  2025-04-22               1.61
3               3                 25  2025-08-29               1.25
4               1                  0         NaN                NaN

   calculated_host_listings_count  availability_365  number_of_reviews_ltm  \
0                               1                83                      0
1                              71               196                      4
2                               1               291                     16
3                              59                78                      9
4                              20               317                      0

   license
0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood_group',
       'neighbourhood', 'latitude', 'longitude', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'availability_365', 'number_of_reviews_ltm', 'license'],
      dtype='object')
['Queenstown-Lakes District' 'Mackenzie District' 'Southland District'
 'Auckland' 'Christchurch City' 'Thames-Coromandel District'
 'Taupo District' 'Far North District' 'New Plymouth District'
 'Marlborough District' 'Selwyn District' 'Wellington City'
 'Ruapehu District' 'Tauranga City' 'Dunedin City'
 'Western Bay of Plenty District' 'Manawatu District' 'Whakatane District'
 'Tasman District' 'Nelson City' 'Kaipara District'
 'Palmerston North City' 'Hamilton City' 'Napier City'
 'Whangarei District' 'Hurunui District' 'Waipa District'
 'Matamata-Piako District' 'Kapiti Coast District' 'Hastings District'
 'Waikato District' 'Rotorua District' 'Central Otago District'
 'South Taranaki District' 'Gisborne District' 'Invercargill City'
 'Ōtorohanga District' 'Lower Hutt City' 'Waitaki District'
 'Ashburton District' 'Buller District' 'South Wairarapa District'
 'Whanganui District' 'Westland District' 'Timaru District'
 'Grey District' 'Clutha District' 'Carterton District' 'Hauraki District'
 'Upper Hutt City' 'Masterton District' 'Tararua District'
 'Kaikoura District' 'Ōpōtiki District' 'Stratford District'
 "Central Hawke's Bay District" 'Waimakariri District' 'Wairoa District'
 'Porirua City' 'Chatham Islands Territory' 'Waitomo District'
 'South Waikato District' 'Rangitikei District' 'Gore District'
 'Horowhenua District' 'Waimate District' 'Kawerau District']
                        id                                           name  \
4                 40183765                       Ensuite Cabin (Sleeps 6)
54     1149729199964166318                 Handy city center. Simple room
69                 1097487                     Heritage Magic in Merivale
74     1339647508906377362                        Settle into the sun set
76     1211070132323635531                            Eco Spa-bath Studio
...                    ...                                            ...
47715  1161213044338512029       Bright & Airy on Tuam - 2 Beds Apartment
47716  1180667042629129011    Central city sunsets - Warm! Modern! Quiet!
47733  1424846609710116983  Upper floor studio 1 bed 1 bath with sofa bed
47735  1395109904560781257                   Cozy guesthouse in casebrook
47750  1051269971528217000      Spacious and Tranquil 4 Bed House Near UC

         host_id                 host_name neighbourhood_group  \
4       98758734  North South Holiday Park   Christchurch City
54     298456605                      Tony   Christchurch City
69       4993285                  Paulette   Christchurch City
74      54299306                    Sarena   Christchurch City
76     179297759                      Peng   Christchurch City
...          ...                       ...                 ...
47715  202585247                     Ohana   Christchurch City
47716  482671075             Paula Corinne   Christchurch City
47733  482671075             Paula Corinne   Christchurch City
47735  433251428                     Donna   Christchurch City
47750   49642171                    Xihang   Christchurch City

        neighbourhood   latitude   longitude        room_type  price  \
4       Harewood Ward -43.470020  172.570880     Private room    NaN
54       Central Ward -43.532700  172.664030     Private room    NaN
69     Fendalton Ward -43.511490  172.625400     Private room  166.0
74       Burwood Ward -43.482864  172.668660  Entire home/apt    NaN
76     Riccarton Ward -43.538437  172.578953     Private room  126.0
...               ...        ...         ...              ...    ...
47715    Central Ward -43.535478  172.635144  Entire home/apt  147.0
47716    Central Ward -43.537523  172.638452  Entire home/apt  268.0
47733    Central Ward -43.537800  172.641679  Entire home/apt  126.0
47735   Harewood Ward -43.478480  172.602470  Entire home/apt  102.0
47750  Riccarton Ward -43.518466  172.570730  Entire home/apt  211.0

       minimum_nights  number_of_reviews last_review  reviews_per_month  \
4                   1                  0         NaN                NaN
54                  1                 25  2025-07-15               1.47
69                  1                230  2025-03-03               2.17
74                  2                  2  2025-04-26               0.35
76                  1                  8  2025-03-01               0.58
...               ...                ...         ...                ...
47715               1                133  2025-10-01               7.95
47716               1                 49  2025-09-24               3.15
47733               1                 17  2025-09-27               3.75
47735               1                  3  2025-08-16               0.51
47750               1                 45  2025-07-10               2.16

       calculated_host_listings_count  availability_365  \
4                                  20               317
54                                  6                 0
69                                  1               221
74                                  1                 0
76                                 20               359
...                               ...               ...
47715                             121                35
47716                             124               285
47733                             124               239
47735                               1               160
47750                              88               133

       number_of_reviews_ltm  license
4                          0      NaN
54                        21      NaN
69                        14      NaN
74                         2      NaN
76                         5      NaN
...                      ...      ...
47715                     90      NaN
47716                     42      NaN
47733                     17      NaN
47735                      3      NaN
47750                     20      NaN

[2991 rows x 18 columns]
New column 'month_year' added successfully!
4        10-2025
54       10-2025
69       10-2025
74       10-2025
76       10-2025
          ...
47715    10-2025
47716    10-2025
47733    10-2025
47735    10-2025
47750    10-2025
Name: month_year, Length: 2991, dtype: object

=== CONCATENATION PROCESS FOR CHRISTCHURCH===
Processing files...

C:\Users\CFakaosi\AppData\Local\Temp\ipykernel_32028\532556256.py:216: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  listings_05_10_2025['month_year'] = '10-2025'

FileNotFoundError: [Errno 2] No such file or directory: 'listings_20_06_2026.csv'

In [5]:
import os

print(os.path.exists(r"C:\DATA422\Data Wrangling\listings_19062026.csv"))

False

In [7]:
import os
print(os.getcwd())

C:\Users\CFakaosi

In [12]:
#query the API for latitude and longitude in the cleaned dataset
#read csv
christchurch_airbnb_cleaned = pd.read_csv(r"C:\Users\CFakaosi\Data Wrangling\christchurch_airbnb_clean.csv")
christchurch_airbnb_cleaned.head()

,id,name,host_id,host_name,neighbourhood,latitude,longitude,room_type,price,price_was_missing,minimum_nights,number_of_reviews,calculated_host_listings_count,availability_365,number_of_reviews_ltm,month_year,listing_price_median,price_ratio_to_listing_median,potential_price_outlier
0,40183765,Ensuite Cabin (Sleeps 6),98758734.0,North South Holiday Park,Harewood Ward,-43.470020,172.570880,Private room,NaN,True,1.0,0,20.0,317,0,10_2025,180.0,NaN,False
1,872901448582963487,The City's Best Kept Secret 2 Bed 2 Bath,482671075.0,Paula Corinne,Central Ward,-43.531286,172.645005,Entire home/apt,182.0,False,1.0,31,124.0,226,19,10_2025,211.0,0.862559,False
2,1504173086779310217,Private ground floor space with its own entrance,572202728.0,Angela,Coastal Ward,-43.486116,172.718882,Private room,77.0,False,1.0,0,1.0,244,0,10_2025,120.0,0.641667,False
3,740243619957183061,Parkside Retreat-Modern Comfort Near the Hospital,264130845.0,Kim,Central Ward,-43.538638,172.621479,Entire home/apt,155.0,False,2.0,57,2.0,325,17,10_2025,230.0,0.673913,False
4,24757121,Brockworth Cottage,186391483.0,John,Riccarton Ward,-43.535000,172.609730,Entire home/apt,265.0,False,2.0,32,1.0,297,0,10_2025,265.0,1.000000,False

In [13]:
#installing and importing the tools for api request
!pip install requests pandas
import requests
import pandas as pd

Requirement already satisfied: requests in .\appdata\local\miniconda3\envs\geo_env\lib\site-packages (2.32.5)
Requirement already satisfied: pandas in .\appdata\local\miniconda3\envs\geo_env\lib\site-packages (2.3.1)
Requirement already satisfied: charset_normalizer<4,>=2 in .\appdata\local\miniconda3\envs\geo_env\lib\site-packages (from requests) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in .\appdata\local\miniconda3\envs\geo_env\lib\site-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in .\appdata\local\miniconda3\envs\geo_env\lib\site-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in .\appdata\local\miniconda3\envs\geo_env\lib\site-packages (from requests) (2026.5.20)
Requirement already satisfied: numpy>=1.22.4 in .\appdata\local\miniconda3\envs\geo_env\lib\site-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in .\appdata\local\miniconda3\envs\geo_env\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in .\appdata\local\miniconda3\envs\geo_env\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in .\appdata\local\miniconda3\envs\geo_env\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in .\appdata\local\miniconda3\envs\geo_env\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [14]:
#reverse geocoding
import geopandas as gpd
from shapely.geometry import Point

In [15]:
#create geometry from latitude and longitude
gdf = gpd.GeoDataFrame(
    christchurch_airbnb_cleaned,
    geometry=gpd.points_from_xy(christchurch_airbnb_cleaned.longitude, christchurch_airbnb_cleaned.latitude),
    crs="EPSG:4326"
)

In [20]:
#loading the boundaries from the Statistical Area 2 2026 layer (Stats NZ) shapefile
sa2 = pd.read_csv(r"C:\Users\CFakaosi\Data Wrangling\statistical-area-2-2026.csv")

In [21]:
#checking dataset before spatial join
sa2[['SA22026_V1_00', 'SA22026_V1_00_NAME']].head()

   SA22026_V1_00         SA22026_V1_00_NAME
0         100100                 North Cape
1         100200           Rangaunu Harbour
2         100301  Inlets Far North District
3         100400         Karikari Peninsula
4         100500                   Tangonge

In [22]:
print(sa2.columns.tolist())

['WKT', 'SA22026_V1_00', 'SA22026_V1_00_NAME', 'SA22026_V1_00_NAME_ASCII', 'LAND_AREA_SQ_KM', 'AREA_SQ_KM', 'Shape_Length']

In [23]:
print(sa2.head())
print(sa2.dtypes)

                                                 WKT  SA22026_V1_00  \
0  MULTIPOLYGON (((1613263.568 6146781.2045,16132...         100100
1  MULTIPOLYGON (((1628575.574 6122952.758,162874...         100200
2  MULTIPOLYGON (((1707298.0265 6089580.4805,1707...         100301
3  MULTIPOLYGON (((1635647.892 6140724.2925,16356...         100400
4  MULTIPOLYGON (((1623667.9915 6112971.3855,1623...         100500

          SA22026_V1_00_NAME   SA22026_V1_00_NAME_ASCII  LAND_AREA_SQ_KM  \
0                 North Cape                 North Cape       829.188671
1           Rangaunu Harbour           Rangaunu Harbour       274.032637
2  Inlets Far North District  Inlets Far North District         0.000000
3         Karikari Peninsula         Karikari Peninsula       174.443022
4                   Tangonge                   Tangonge       177.160932

   AREA_SQ_KM  Shape_Length
0  829.188671  4.169381e+05
1  274.032637  1.492633e+05
2  623.322322  1.352685e+06
3  174.443022  1.403891e+05
4  177.160932  1.015090e+05
WKT                          object
SA22026_V1_00                 int64
SA22026_V1_00_NAME           object
SA22026_V1_00_NAME_ASCII     object
LAND_AREA_SQ_KM             float64
AREA_SQ_KM                  float64
Shape_Length                float64
dtype: object

In [24]:
print(type(sa2["WKT"].iloc[0]))

<class 'str'>

In [25]:
from shapely import wkt
import geopandas as gpd

sa2["geometry"] = sa2["WKT"].apply(wkt.loads)
sa2 = gpd.GeoDataFrame(sa2, geometry="geometry", crs="EPSG:4326")

In [26]:
print(type(sa2.geometry.iloc[0]))

<class 'shapely.geometry.multipolygon.MultiPolygon'>

In [28]:
#spatial join between Christchurch clean dataset and the Statistical Area 2 2026 dataset
result = gpd.sjoin(
    gdf,
    sa2[["SA22026_V1_00", "SA22026_V1_00_NAME", "geometry"]],
    how="left",
    predicate="within"
)

In [29]:
#checking output
print(result[["latitude", "longitude", "SA22026_V1_00", "SA22026_V1_00_NAME"]].head())

    latitude   longitude  SA22026_V1_00 SA22026_V1_00_NAME
0 -43.470020  172.570880            NaN                NaN
1 -43.531286  172.645005            NaN                NaN
2 -43.486116  172.718882            NaN                NaN
3 -43.538638  172.621479            NaN                NaN
4 -43.535000  172.609730            NaN                NaN

In [31]:
print(sa2.total_bounds)

[1067061.1995     4701317.1815     2519681.59640929 6220662.37427826]

In [32]:
print(sa2.crs)

EPSG:4326

In [33]:
print(sa2.geometry.iloc[0])

MULTIPOLYGON (((1613263.568 6146781.2045, 1613267.663 6146779.912, 1613270.2205 6146777.859, 1613276.845 6146766.5955, 1613278.3655 6146761.991, 1613282.1785 6146753.0365, 1613284.98 6146747.9165, 1613290.071 6146737.6795, 1613294.1505 6146732.0435, 1613295.43 6146731.273, 1613303.362 6146727.4115, 1613313.6005 6146723.5415, 1613320.985 6146709.976, 1613322.505 6146704.8595, 1613326.3195 6146696.417, 1613330.657 6146690.781, 1613335.2545 6146686.165, 1613339.5995 6146682.573, 1613343.1745 6146678.982, 1613347.778 6146676.41, 1613355.199 6146673.0615, 1613393.0625 6146653.7625, 1613402.2605 6146645.299, 1613405.06 6146639.669, 1613407.091 6146634.04, 1613411.162 6146625.595, 1613420.3475 6146614.0655, 1613425.9665 6146608.4255, 1613433.888 6146601.498, 1613459.9705 6146584.796, 1613465.083 6146580.9465, 1613473.01 6146575.8075, 1613488.357 6146566.81, 1613500.3705 6146557.568, 1613504.2015 6146554.2335, 1613507.113 6146552.165, 1613509.1165 6146550.6485, 1613510.9155 6146547.936, 1613512.613 6146544.762, 1613515.9835 6146542.1125, 1613519.195 6146541.0375, 1613523.142 6146539.6735, 1613526.335 6146537.4915, 1613529.059 6146534.8535, 1613532.614 6146532.294, 1613535.8035 6146529.835, 1613538.7885 6146526.267, 1613541.498 6146522.7995, 1613544.581 6146519.509, 1613547.4715 6146515.8525, 1613549.445 6146512.488, 1613550.3915 6146508.496, 1613551.717 6146505.051, 1613553.2385 6146502.2505, 1613555.8745 6146499.8015, 1613558.607 6146497.6275, 1613562.0855 6146495.809, 1613565.7485 6146493.989, 1613569.225 6146492.08, 1613574.0525 6146488.112, 1613579.2415 6146483.676, 1613584.148 6146478.969, 1613588.613 6146475.3785, 1613593.1895 6146472.895, 1613596.191 6146470.1625, 1613598.697 6146465.4035, 1613601.8515 6146460.819, 1613604.959 6146458.824, 1613608.723 6146457.4655, 1613613.3395 6146457.294, 1613615.323 6146459.851, 1613617.353 6146459.724, 1613619.2715 6146458.396, 1613647.254 6146463.459, 1613658.235 6146455.011, 1613658.63 6146447.8525, 1613659.1105 6146437.94, 1613659.675 6146434.3885, 1613660.2965 6146427.8875, 1613656.9635 6146423.1515, 1613652.995 6146397.7185, 1613653.6735 6146390.6905, 1613654.309 6146383.4855, 1613661.629 6146373.1075, 1613666.8605 6146351.147, 1613667.4475 6146344.058, 1613666.1595 6146337.737, 1613666.1965 6146330.856, 1613666.715 6146323.7805, 1613667.1825 6146316.686, 1613667.5395 6146309.609, 1613668.561 6146302.5915, 1613668.6235 6146295.5605, 1613668.6145 6146288.4855, 1613668.4105 6146281.42, 1613669.1655 6146273.686, 1613669.1715 6146266.371, 1613668.082 6146259.5195, 1613667.5985 6146257.228, 1613665.7935 6146250.5645, 1613662.989 6146244.246, 1613661.0995 6146237.427, 1613658.9495 6146230.6895, 1613656.946 6146223.878, 1613649.9725 6146203.7205, 1613645.07 6146198.078, 1613642.1905 6146191.6155, 1613640.5115 6146184.696, 1613640.036 6146177.365, 1613638.3025 6146170.862, 1613637.8525 6146168.7555, 1613636.8595 6146161.843, 1613636.128 6146154.754, 1613634.7845 6146148.1895, 1613632.612 6146142.413, 1613630.1015 6146137.0015, 1613627.6215 6146131.662, 1613625.807 6146126.0925, 1613625.629 6146119.9785, 1613627.2655 6146109.6615, 1613627.234 6146102.627, 1613627.26 6146095.587, 1613625.593 6146090.8285, 1613626.061 6146062.0235, 1613627.5565 6146048.797, 1613627.3465 6146034.8045, 1613627.225 6146020.81, 1613627.198 6146013.8125, 1613627.192 6146006.815, 1613627.246 6145992.8205, 1613627.307 6145985.823, 1613627.495 6145971.828, 1613627.7715 6145957.8365, 1613627.9425 6145950.8405, 1613628.1365 6145943.8465, 1613628.4295 6145937.069, 1613629.1405 6145923.0935, 1613631.149 6145888.155, 1613631.8675 6145874.1795, 1613632.174 6145867.191, 1613632.4335 6145860.199, 1613632.6395 6145853.207, 1613632.7815 6145846.213, 1613632.8595 6145836.3135, 1613632.945 6145834.3155, 1613633.8385 6145827.5055, 1613635.5615 6145820.875, 1613637.986 6145814.397, 1613640.983 6145808.046, 1613644.429 6145801.7995, 1613648.1945 6145795.63, 1613652.1555 6145789.514, 1613656.1835 6145783.4255, 1613666.097 6145686.176, 1613681.972 6145562.88, 1613687.2635 6145522.663, 1613684.0885 6145494.617, 1613678.797 6145470.8045, 1613670.8595 6145455.988, 1613673.5055 6145439.5835, 1613681.972 6145423.1795, 1613673.5055 6145414.1835, 1613661.8635 6145402.542, 1613638.8975 6145392.858, 1613603.179 6145373.0145, 1613572.2225 6145360.3145, 1613549.204 6145351.583, 1613547.6165 6145334.9145, 1613573.81 6145311.102, 1613608.735 6145273.0015, 1613639.6915 6145234.9015, 1613640.485 6145203.1515, 1613655.5665 6145172.195, 1613666.679 6145142.0325, 1613664.298 6145103.9325, 1613655.5665 6145065.8325, 1613631.0925 6145034.347, 1613608.603 6145013.974, 1613596.961 6145017.6785, 1613579.763 6145029.849, 1613560.978 6145036.199, 1613550.13 6145035.141, 1613537.6945 6145021.3825, 1613532.138 6145006.5655, 1613532.6675 6144989.897, 1613544.0445 6144971.6405, 1613542.986 6144965.82, 1613539.0175 6144943.0655, 1613527.905 6144934.3345, 1613528.1695 6144928.778, 1613534.784 6144920.576, 1613549.6005 6144911.58, 1613568.6505 6144900.732, 1613573.1485 6144891.207, 1613561.507 6144876.126, 1613545.103 6144855.4885, 1613530.0215 6144829.03, 1613515.205 6144816.859, 1613497.213 6144808.657, 1613472.607 6144806.5405, 1613460.1715 6144800.455, 1613448.5295 6144762.6195, 1613431.5965 6144721.3445, 1613432.6545 6144699.6485, 1613435.036 6144672.1315, 1613445.3545 6144631.386, 1613460.965 6144576.3525, 1613485.042 6144524.2295, 1613497.742 6144493.0085, 1613503.034 6144477.927, 1613505.9445 6144456.496, 1613508.061 6144439.298, 1613505.415 6144389.027, 1613505.415 6144360.981, 1613507.7965 6144345.3705, 1613515.4695 6144319.177, 1613534.255 6144298.01, 1613543.5155 6144287.162, 1613542.986 6144275.5205, 1613530.286 6144254.089, 1613519.9675 6144239.537, 1613520.232 6144219.6935, 1613527.111 6144192.441, 1613538.488 6144164.66, 1613555.9505 6144127.3535, 1613569.18 6144117.2995, 1613584.526 6144114.1245, 1613602.4365 6144107.5755, 1613605.4165 6144104.4015, 1613609.552 6144100.488, 1613614.213 6144096.3355, 1613626.33 6144079.1995, 1613635.8615 6144066.2365, 1613637.432 6144060.684, 1613637.553 6144056.943, 1613637.1925 6144050.3045, 1613634.298 6144043.5445, 1613627.653 6144030.2515, 1613618.9215 6144019.9325, 1613612.836 6144008.82, 1613609.926 6143991.3575, 1613612.836 6143979.451, 1613618.9215 6143971.5135, 1613630.5635 6143966.222, 1613641.4115 6143964.1055, 1613651.73 6143967.545, 1613661.784 6143984.2135, 1613669.722 6143994.268, 1613677.3945 6143998.501, 1613685.597 6143997.972, 1613690.624 6143986.066, 1613690.624 6143970.9845, 1613692.476 6143960.6655, 1613691.153 6143938.4405, 1613688.2425 6143922.0365, 1613690.0945 6143908.278, 1613707.4415 6143886.846, 1613711.5485 6143880.21, 1613715.046 6143874.533, 1613717.705 6143870.7955, 1613719.7525 6143867.534, 1613723.853 6143861.3715, 1613727.0925 6143855.441, 1613729.854 6143849.7515, 1613732.4 6143845.658, 1613735.317 6143840.97, 1613736.4055 6143838.316, 1613739.7295 6143832.711, 1613742.1 6143827.5915, 1613745.352 6143821.796, 1613748.252 6143816.968, 1613751.4965 6143809.2285, 1613776.349 6143795.301, 1613790.1075 6143783.3945, 1613813.6555 6143771.753, 1613828.7365 6143763.8155, 1613858.6345 6143757.2005, 1613866.3075 6143749.528, 1613880.595 6143720.4235, 1613898.587 6143688.1445, 1613907.318 6143671.4755, 1613914.492 6143647.9055, 1613923.6555 6143640.027, 1613931.395 6143634.434, 1613934.041 6143627.819, 1613933.6 6143612.8525, 1613929.2985 6143597.5925, 1613923.954 6143588.76, 1613921.1755 6143580.4255, 1613926.5335 6143573.6915, 1613935.86 6143564.1535, 1613941.813 6143551.4535, 1613946.179 6143530.816, 1613954.578 6143500.0395, 1613964.5035 6143488.3695, 1613976.3415 6143476.841, 1613995.7815 6143470.137, 1614002.1385 6143461.363, 1614014.8385 6143456.2035, 1614033.6595 6143457.7645, 1614041.826 6143458.5845, 1614048.9695 6143453.8225, 1614051.748 6143443.9005, 1614047.3825 6143424.4535, 1614051.3515 6143414.532, 1614058.099 6143401.0385, 1614064.846 6143391.5135, 1614079.5315 6143382.783, 1614090.2475 6143376.83, 1614093.821 6143359.368, 1614098.9815 6143349.05, 1614114.859 6143335.5575, 1614126.37 6143326.033, 1614133.914 6143310.5565, 1614140.267 6143295.8735, 1614160.907 6143278.8085, 1614172.417 6143265.315, 1614183.926 6143258.568, 1614193.0535 6143254.599, 1614137.046 6143223.6675, 1614125.2665 6143218.4475, 1613639.0725 6143002.658, 1613542.822 6142959.863, 1613406.028 6142899.122, 1613401.205 6142897.124, 1613305.5085 6142854.645, 1613296.1295 6142845.7265, 1613195.276 6143026.8565, 1613180.4355 6143036.0065, 1613183.8185 6143013.4735, 1613185.5125 6142990.5825, 1613185.726 6142977.8475, 1613184.906 6142963.558, 1613182.3825 6142943.8395, 1613178.829 6142924.052, 1613174.284 6142905.454, 1613167.4855 6142885.839, 1613159.7475 6142868.2135, 1613150.621 6142850.229, 1613140.258 6142833.352, 1613129.9025 6142818.562, 1613113.757 6142798.416, 1613057.9085 6142733.584, 1613035.1455 6142724.8735, 1612848.883 6142648.908, 1612829.868 6142640.566, 1612637.6695 6142558.3685, 1612174.3785 6142359.5365, 1611881.2535 6142234.093, 1611877.85 6142232.3535, 1611867.928 6142159.64, 1611845.363 6142086.0355, 1611901.572 6141917.6625, 1611949.7425 6141853.692, 1611961.885 6141855.0545, 1612199.6165 6141722.9435, 1612298.09 6141659.035, 1612359.4865 6141618.8805, 1612434.4265 6141497.254, 1612482.682 6141365.829, 1611733.424 6141125.926, 1610451.125 6140733.339, 1609806.6945 6140541.4455, 1609379.4395 6140473.292, 1609358.225 6140469.9075, 1607011.5225 6140095.573, 1606530.535 6139986.5835, 1606504.699 6139980.734, 1606468.626 6139972.5645, 1606468.0725 6139973.4835, 1606465.498 6139977.137, 1606450.272 6139994.3865, 1606443.0685 6140005.8655, 1606441.778 6140007.173, 1606434.83 6140018.1305, 1606429.9505 6140026.998, 1606424.029 6140035.87, 1606422.493 6140039.259, 1606420.176 6140042.652, 1606416.5785 6140049.1695, 1606415.8105 6140050.9945, 1606414.0075 6140053.6055, 1606412.4735 6140057.253, 1606404.2585 6140072.8965, 1606401.4305 6140077.5915, 1606398.851 6140080.726, 1606397.0495 6140083.5955, 1606392.1465 6140089.0845, 1606378.713 6140102.1645, 1606369.926 6140110.0165, 1606365.264 6140112.907, 1606363.197 6140114.738, 1606358.8095 6140119.7035, 1606354.4185 6140124.1495, 1606350.0395 6140130.154, 1606328.883 6140154.717, 1606319.35 6140167.77, 1606311.412 6140185.7515, 1606308.589 6140191.4865, 1606307.314 6140195.1325, 1606305.257 6140198.5235, 1606302.948 6140203.216, 1606295.538 6140222.4905, 1606290.6985 6140237.3315, 1606288.649 6140242.022, 1606280.6685 6140253.7675, 1606278.3615 6140258.7185, 1606272.4295 6140266.0325, 1606270.105 6140268.128, 1606267.2565 6140269.9655, 1606265.4485 6140271.7945, 1606264.153 6140272.5845, 1606260.538 6140276.2445, 1606257.446 6140280.422, 1606253.3085 6140283.8275, 1606250.9845 6140286.1815, 1606248.9245 6140289.312, 1606239.6125 6140296.39, 1606231.8585 6140303.4555, 1606230.573 6140305.543, 1606227.209 6140308.1625, 1606211.7095 6140323.075, 1606210.676 6140324.122, 1606209.639 6140324.6475, 1606208.6085 6140325.953, 1606206.797 6140327.265, 1606204.214 6140329.88, 1606200.855 6140333.0205, 1606198.5225 6140334.0755, 1606196.1985 6140336.6885, 1606190.2505 6140341.404, 1606187.152 6140344.5425, 1606179.129 6140350.3125, 1606175.5005 6140352.154, 1606169.029 6140356.354, 1606167.2225 6140358.4455, 1606163.3435 6140361.588, 1606157.9275 6140368.1195, 1606154.089 6140377.2395, 1606153.076 6140381.4025, 1606152.579 6140384.7835, 1606146.242 6140408.9885, 1606140.616 6140422.7965, 1606138.8145 6140425.6665, 1606135.487 6140433.483, 1606134.4705 6140436.866, 1606132.4155 6140440.778, 1606130.891 6140445.9855, 1606128.8425 6140450.674, 1606122.677 6140461.8875, 1606120.8875 6140466.317, 1606119.0895 6140469.706, 1606118.837 6140470.747, 1606117.037 6140473.6165, 1606114.2025 6140477.533, 1606113.431 6140478.8365, 1606109.8175 6140482.7575, 1606105.1945 6140491.362, 1606101.6085 6140499.4395, 1606082.3005 6140528.148, 1606078.432 6140532.8505, 1606076.634 6140535.981, 1606071.2645 6140549.5265, 1606069.216 6140554.2165, 1606054.286 6140576.6605, 1606051.197 6140581.098, 1606049.13 6140583.19, 1606046.2935 6140586.846, 1606043.72 6140590.76, 1606033.6705 6140604.3365, 1606008.6325 6140631.524, 1606006.3035 6140633.359, 1605999.3425 6140641.978, 1605997.801 6140644.8455, 1605995.993 6140646.6765, 1605991.0955 6140653.206, 1605988.7715 6140655.5585, 1605986.185 6140657.654, 1605980.76 6140662.8865, 1605977.9145 6140664.984, 1605974.039 6140668.648, 1605961.9385 6140686.395, 1605959.883 6140690.3055, 1605957.3355 6140698.116, 1605954.771 6140703.3295, 1605952.196 6140706.9855, 1605938.5105 6140721.366, 1605935.1475 6140723.9855, 1605931.0185 6140728.4295, 1605928.9595 6140731.5615, 1605921.4805 6140740.704, 1605919.938 6140743.313, 1605915.8405 6140752.6935, 1605912.249 6140759.991, 1605910.7045 6140762.341, 1605907.8895 6140769.1145, 1605906.0945 6140772.764, 1605904.2945 6140775.634, 1605894.2445 6140789.21, 1605890.6305 6140793.1325, 1605877.7655 6140813.2235, 1605874.152 6140817.144, 1605872.0205 6140821.3245, 1605866.5125 6140830.5065, 1605861.302 6140840.701, 1605849.7865 6140859.34, 1605846.399 6140864.085, 1605839.804 6140871.776, 1605836.843 6140874.4575, 1605834.9045 6140877.0965, 1605832.4555 6140879.7555, 1605826.958 6140889.1925, 1605826.0305 6140891.533, 1605822.216 6140898.3425, 1605817.41 6140912.1, 1605815.758 6140915.4945, 1605811.1685 6140922.081, 1605806.6185 6140929.6875, 1605800.7605 6140936.5815, 1605793.76 6140946.849, 1605790.7135 6140953.6245, 1605789.9035 6140958.776, 1605787.5795 6140964.5, 1605785.47 6140969.192, 1605783.5635 6140972.5975, 1605768.9055 6140989.5755, 1605766.435 6140991.7245, 1605755.675 6141003.937, 1605750.572 6141010.544, 1605746.8865 6141014.278, 1605742.0085 6141020.1085, 1605739.0475 6141022.7905, 1605731.686 6141030.513, 1605728.4785 6141033.4595, 1605716.464 6141046.2365, 1605714.035 6141049.4055, 1605710.3495 6141053.1395, 1605705.4605 6141058.715, 1605703.3395 6141063.152, 1605701.72 6141067.3115, 1605695.669 6141075.749, 1605693.2185 6141078.408, 1605689.2555 6141081.6415, 1605684.644 6141087.7175, 1605684.1755 6141088.76, 1605681.9605 6141090.898, 1605679.7855 6141094.058, 1605677.5815 6141096.451, 1605675.8985 6141099.0785, 1605673.2135 6141102.261, 1605672.01 6141104.1005, 1605667.589 6141108.6315, 1605658.3205 6141125.9, 1605652.195 6141132.55, 1605646.9975 6141136.8575, 1605629.494 6141159.326, 1605626.8725 6141164.039, 1605624.561 6141170.0195, 1605619.66 6141181.4795, 1605618.754 6141184.33, 1605614.534 6141193.7145, 1605613.628 6141196.5665, 1605609.325 6141203.907, 1605607.4495 6141208.0795, 1605604.5315 6141211.7815, 1605599.715 6141219.142, 1605595.0485 6141230.081, 1605582.648 6141250.321, 1605581.3805 6141252.392, 1605578.281 6141257.8925, 1605567.393 6141273.18, 1605563.8555 6141280.49, 1605562.661 6141282.587, 1605551.679 6141295.5755, 1605545.7675 6141301.192, 1605542.8695 6141305.406, 1605540.92 6141307.7875, 1605537.788 6141312.523, 1605532.1415 6141318.385, 1605521.0315 6141334.4495, 1605517.1425 6141339.4715, 1605512.05 6141346.3335, 1605508.4925 6141353.1335, 1605498.318 6141367.112, 1605495.858 6141369.516, 1605493.4395 6141372.9425, 1605490.8505 6141378.422, 1605488.5275 6141384.1455, 1605485.0015 6141391.7105, 1605481.145 6141397.498, 1605480.462 6141399.574, 1605479.483 6141400.6375, 1605472.5795 6141413.202, 1605470.8855 6141415.574, 1605467.051 6141421.8735, 1605463.1295 6141426.1285, 1605458.0905 6141434.2675, 1605456.9285 6141437.1295, 1605455.224 6141439.2465, 1605452.8395 6141443.438, 1605447.458 6141449.546, 1605446.0415 6141452.419, 1605437.23 6141468.389, 1605434.8655 6141473.0905, 1605432.9065 6141475.219, 1605430.2535 6141479.1645, 1605424.777 6141489.1135, 1605423.6045 6141491.72, 1605418.055 6141499.8815, 1605416.0945 6141502.008, 1605413.442 6141505.9555, 1605403.2685 6141519.934, 1605398.624 6141525.243, 1605392.7975 6141532.9035, 1605385.414 6141546.256, 1605383.23 6141549.161, 1605380.0235 6141552.107, 1605365.324 6141568.064, 1605360.338 6141572.5395, 1605359.6465 6141573.159, 1605348.577 6141584.107, 1605340.3645 6141595.959, 1605337.0085 6141601.4705, 1605319.612 6141626.493, 1605317.705 6141629.8985, 1605311.7935 6141635.515, 1605300.0105 6141653.91, 1605297.327 6141657.0905, 1605294.1205 6141660.0385, 1605287.2915 6141668.25, 1605274.422 6141685.156, 1605269.862 6141692.507, 1605263.7475 6141705.552, 1605261.3505 6141709.488, 1605252.8385 6141720.329, 1605248.769 6141727.1495, 1605241.9615 6141735.8735, 1605239.7465 6141738.0115, 1605236.0805 6141742.257, 1605233.93 6141745.927, 1605226.5575 6141759.534, 1605202.3 6141792.0045, 1605198.71 6141798.0375, 1605194.257 6141807.943, 1605192.35 6141811.3465, 1605188.7165 6141816.359, 1605173.0875 6141840.796, 1605169.679 6141845.0305, 1605167.2925 6141849.2215, 1605167.08 6141850.255, 1605165.6 6141851.5955, 1605154.284 6141868.9475, 1605151.856 6141872.117, 1605148.9795 6141876.8425, 1605143.621 6141883.4585, 1605141.4055 6141885.5985, 1605138.2425 6141889.5645, 1605130.903 6141897.799, 1605120.2075 6141911.5445, 1605111.6535 6141921.3635, 1605108.416 6141923.546, 1605103.025 6141929.395, 1605097.8375 6141933.9595, 1605093.917 6141938.2145, 1605093.2035 6141939.5235, 1605089.5175 6141943.257, 1605085.864 6141947.7575, 1605084.128 6141949.1095, 1605077.268 6141956.556, 1605075.105 6141959.971, 1605071.684 6141963.9485, 1605069.267 6141967.3745, 1605064.143 6141973.471, 1605061.9275 6141975.609, 1605059.0185 6141979.5675, 1605048.269 6141998.176, 1605044.679 6142004.2065, 1605043.518 6142007.0705, 1605042.325 6142009.167, 1605040.4815 6142014.1025, 1605039.2975 6142016.454, 1605037.4445 6142021.137, 1605035.527 6142024.2855, 1605019.101 6142041.849, 1605014.0505 6142049.7325, 1605005.709 6142064.6595, 1604999.242 6142075.416, 1604982.5695 6142099.3855, 1604980.376 6142102.0355, 1604978.4475 6142104.929, 1604974.294 6142109.705, 1604969.936 6142115.77, 1604962.9695 6142126.804, 1604960.3055 6142130.4945, 1604958.591 6142132.3565, 1604954.723 6142137.8885, 1604951.409 6142144.422, 1604948.267 6142148.9, 1604945.3905 6142153.6235, 1604939.8295 6142161.5295, 1604937.9335 6142165.1885, 1604935.291 6142169.391, 1604930.4975 6142179.2425, 1604928.6245 6142182.844, 1604924.9295 6142187.4035, 1604916.338 6142200.05, 1604905.821 6142218.237, 1604903.143 6142223.785, 1604901.4495 6142228.066, 1604897.5415 6142235.136, 1604894.101 6142239.945, 1604891.663 6142244.7385, 1604884.8125 6142256.3585, 1604883.108 6142259.8875, 1604880.417 6142264.436, 1604877.4925 6142270.239, 1604869.41 6142283.3785, 1604866.703 6142286.925, 1604864.0155 6142291.7205, 1604862.0755 6142296.2575, 1604856.9305 6142304.5975, 1604852.7455 6142309.917, 1604845.386 6142321.0415, 1604838.04 6142333.1715, 1604825.9845 6142348.8715, 1604824.495 6142349.896, 1604820.0585 6142355.2195, 1604807.8055 6142374.6805, 1604802.428 6142384.2755, 1604801.4475 6142385.7935, 1604798.9735 6142388.083, 1604793.7985 6142394.168, 1604785.6495 6142402.8, 1604781.2285 6142409.125, 1604780.2435 6142410.3915, 1604777.026 6142413.1915, 1604770.36 6142420.301, 1604766.422 6142425.3675, 1604763.74 6142430.666, 1604761.2735 6142433.456, 1604760.0465 6142435.2275, 1604756.097 6142439.5415, 1604753.1545 6142444.0915, 1604741.0765 6142458.292, 1604735.388 6142463.6325, 1604705.0525 6142498.1305, 1604704.0895 6142500.9, 1604699.672 6142507.4745, 1604691.1605 6142525.63, 1604689.4625 6142529.662, 1604682.0955 6142540.2875, 1604678.8955 6142544.3405, 1604675.953 6142548.8925, 1604673.7345 6142551.4275, 1604665.1345 6142563.573, 1604662.175 6142566.8715, 1604660.2095 6142569.656, 1604652.639 6142583.54, 1604639.36 6142601.5135, 1604631.263 6142613.653, 1604626.831 6142619.2255, 1604623.8885 6142623.7755, 1604615.57 6142637.9205, 1604608.4245 6142646.5405, 1604597.8465 6142660.467, 1604595.873 6142662.7505, 1604591.914 6142666.314, 1604588.2125 6142670.3745, 1604578.3995 6142685.291, 1604571.749 6142693.4025, 1604555.551 6142717.428, 1604553.8245 6142719.4565, 1604547.7145 6142730.3

In [34]:
print(sa2.geometry.iloc[0].bounds)

(1566500.2765, 6139972.5645, 1615982.8835, 6194308.4925)

In [35]:
#override the incorrect crs above
sa2 = sa2.set_crs("EPSG:2193", allow_override=True)

In [36]:
#converting to lat/lon
sa2 = sa2.to_crs("EPSG:4326")

In [37]:
print(sa2.total_bounds)

[-177.35790201  -47.72404552  178.83620792  -34.14906503]

In [38]:
result = gpd.sjoin(
    gdf,
    sa2[["SA22026_V1_00", "SA22026_V1_00_NAME", "geometry"]],
    how="left",
    predicate="within"
)

In [39]:
print(result["SA22026_V1_00"].notna().sum())

28795

In [40]:
#codes for each latitude/longitude pairs in the AirBnB dataset below in the SA22026_V1_00 column
print(
    result[
        ["latitude", "longitude", "SA22026_V1_00", "SA22026_V1_00_NAME"]
        ].head()
)

    latitude   longitude  SA22026_V1_00          SA22026_V1_00_NAME
0 -43.470020  172.570880         316700        Christchurch Airport
1 -43.531286  172.645005         327000   Christchurch Central-East
2 -43.486116  172.718882         326000              Waimairi Beach
3 -43.538638  172.621479         327100  Christchurch Central-South
4 -43.535000  172.609730         325200              Riccarton East

In [41]:
#saving results to new csv
result.to_csv("christchurch_airbnb_with_sa2.csv", index=False)

In [44]:
display(result)

,id,name,host_id,host_name,neighbourhood,latitude,longitude,room_type,price,price_was_missing,...,availability_365,number_of_reviews_ltm,month_year,listing_price_median,price_ratio_to_listing_median,potential_price_outlier,geometry,index_right,SA22026_V1_00,SA22026_V1_00_NAME
0,40183765,Ensuite Cabin (Sleeps 6),98758734.0,North South Holiday Park,Harewood Ward,-43.470020,172.570880,Private room,NaN,True,...,317,0,10_2025,180.0,NaN,False,POINT (172.57088 -43.47002),2065,316700,Christchurch Airport
1,872901448582963487,The City's Best Kept Secret 2 Bed 2 Bath,482671075.0,Paula Corinne,Central Ward,-43.531286,172.645005,Entire home/apt,182.0,False,...,226,19,10_2025,211.0,0.862559,False,POINT (172.64501 -43.53129),827,327000,Christchurch Central-East
2,1504173086779310217,Private ground floor space with its own entrance,572202728.0,Angela,Coastal Ward,-43.486116,172.718882,Private room,77.0,False,...,244,0,10_2025,120.0,0.641667,False,POINT (172.71888 -43.48612),2136,326000,Waimairi Beach
3,740243619957183061,Parkside Retreat-Modern Comfort Near the Hospital,264130845.0,Kim,Central Ward,-43.538638,172.621479,Entire home/apt,155.0,False,...,325,17,10_2025,230.0,0.673913,False,POINT (172.62148 -43.53864),2144,327100,Christchurch Central-South
4,24757121,Brockworth Cottage,186391483.0,John,Riccarton Ward,-43.535000,172.609730,Entire home/apt,265.0,False,...,297,0,10_2025,265.0,1.000000,False,POINT (172.60973 -43.535),820,325200,Riccarton East
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28790,1066823401454630151,5 Minute Walk to Arena & Stadium,368515906.0,Jed,Spreydon Ward,-43.547010,172.602990,Entire home/apt,204.0,False,...,293,24,06_2026,204.0,1.000000,False,POINT (172.60299 -43.54701),2128,326100,Addington West
28791,13548527,"""Home away from Home"" - warm, sunny, welcoming.",73257997.0,Keryn,Spreydon Ward,-43.559420,172.615790,Entire home/apt,112.0,False,...,14,16,06_2026,99.5,1.125628,False,POINT (172.61579 -43.55942),829,328200,Spreydon South
28792,822795371090783373,Funky Kiwi Caravan for Two!,1743811.0,Kelly,Spreydon Ward,-43.548410,172.609990,Private room,46.0,False,...,166,12,06_2026,46.0,1.000000,False,POINT (172.60999 -43.54841),2148,327600,Spreydon North
28793,1577389596430670846,Affordable Private Sleep-Out Room #1 Own Entrance,251685150.0,Reshabh,Heathcote Ward,-43.548520,172.643170,Private room,77.0,False,...,314,2,06_2026,77.0,1.000000,False,POINT (172.64317 -43.54852),833,329400,Sydenham North
28794,1437344405173920949,Sumner Views,36077654.0,Simon,Heathcote Ward,-43.574250,172.770590,Entire home/apt,221.0,False,...,296,31,06_2026,221.0,1.000000,False,POINT (172.77059 -43.57425),842,332700,Sumner

In [47]:
#renaming the SA22026_V1_00 column to area_code and SA22026_V1_00_NAME to area_name
result = result.rename(columns={
    "SA22026_V1_00": "area_code",
    "SA22026_V1_00_NAME": "area_name"
})
print(result.columns)

Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood', 'latitude',
       'longitude', 'room_type', 'price', 'price_was_missing',
       'minimum_nights', 'number_of_reviews', 'calculated_host_listings_count',
       'availability_365', 'number_of_reviews_ltm', 'month_year',
       'listing_price_median', 'price_ratio_to_listing_median',
       'potential_price_outlier', 'geometry', 'index_right', 'area_code',
       'area_name'],
      dtype='object')

In [48]:
central = result[
    result["area_name"].str.contains("Christchurch Central", na=False)
    ]
print("Median price:", central["price"].median())

Median price: 220.0

In [ ]:
#checking which part of Christchurch we observe the largest gap between short and long term rental prices

In [2]:
import os
os.getcwd()

'C:\\Users\\CFakaosi'

In [4]:
import os

for root, dirs, files in os.walk(r"C:\Users\CFakaosi"):
    if "New-Zealand-Tenancy-Data-Wrangling" in dirs:
        print(os.path.join(root, "New-Zealand-Tenancy-Data-Wrangling"))
        break

In [7]:
%cd "C:\DATA422\Group Project\New-Zealand-Tenancy-Data-Wrangling"

C:\DATA422\Group Project\New-Zealand-Tenancy-Data-Wrangling

In [8]:
!git branch

  carolina
* jayant
  main

In [9]:
!git checkout -b carolina-fakaosi

Switched to a new branch 'carolina-fakaosi'

In [10]:
!git branch -m carolina-deliverable-5

In [11]:
!git branch

  carolina
* carolina-deliverable-5
  jayant
  main

In [12]:
!git push -u origin carolina-deliverable-5

branch 'carolina-deliverable-5' set up to track 'origin/carolina-deliverable-5'.

remote:
remote: Create a pull request for 'carolina-deliverable-5' on GitHub by visiting:
remote:      https://github.com/jochani/New-Zealand-Tenancy-Data-Wrangling/pull/new/carolina-deliverable-5
remote:
To https://github.com/jochani/New-Zealand-Tenancy-Data-Wrangling.git
 * [new branch]      carolina-deliverable-5 -> carolina-deliverable-5

In [13]:
!git branch

  carolina
* carolina-deliverable-5
  jayant
  main

In [14]:
!git status

On branch carolina-deliverable-5
Your branch is up to date with 'origin/carolina-deliverable-5'.

nothing to commit, working tree clean

In [15]:
!dir

 Volume in drive C is Windows
 Volume Serial Number is 560B-9C39

 Directory of C:\DATA422\Group Project\New-Zealand-Tenancy-Data-Wrangling

29/07/2026  01:14 am    <DIR>          .
09/09/2026  07:57 pm    <DIR>          ..
29/07/2026  12:18 am             4,846 .gitignore
29/07/2026  01:13 am                80 hello_jay.txt
29/07/2026  12:18 am                78 README.md
               3 File(s)          5,004 bytes
               2 Dir(s)  253,230,751,744 bytes free

In [17]:
import os
os.getcwd()

'C:\\DATA422\\Group Project\\New-Zealand-Tenancy-Data-Wrangling'

In [18]:
import os

for root, dirs, files in os.walk(r"C:\DATA422"):
    for file in files:
        if "Deliverable" in file:
            print(os.path.join(root, file))

C:\DATA422\Group Project\Listings_dataset_Oct25_June26\analysis\Deliverable_3_ImprovedCode.py
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\analysis\Deliverable_3_OriginalCode.py

In [20]:
for root, dirs, files in os.walk(r"C:\DATA422"):
    for file in files:
        if "Deliverable_5" in file or "Deliverable 5" in file:
            print(os.path.join(root, file))

In [21]:
for root, dirs, files in os.walk(r"C:\DATA422"):
    for file in files:
        if file.endswith(".ipynb"):
            print(os.path.join(root, file))

In [22]:
for root, dirs, files in os.walk(r"C:\DATA422"):
    for file in files:
        if file.endswith(".py"):
            print(os.path.join(root, file))

C:\DATA422\Group Project\Listings_dataset_Oct25_June26\analysis\Deliverable_3_ImprovedCode.py
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\analysis\Deliverable_3_OriginalCode.py

In [23]:
import os

for root, dirs, files in os.walk(r"C:\DATA422"):
    for file in files:
        print(os.path.join(root, file))

C:\DATA422\Cheat Sheet_MidTerm Test.docx
C:\DATA422\Group Project\listings.csv
C:\DATA422\Group Project\Maori Data Presentation.docx
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.gitignore
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\README.md
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\COMMIT_EDITMSG
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\config
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\description
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\FETCH_HEAD
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\HEAD
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\index
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\ORIG_HEAD
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\hooks\applypatch-msg.sample
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\hooks\commit-msg.sample
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\hooks\fsmonitor-watchman.sample
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\hooks\post-update.sample
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\hooks\pre-applypatch.sample
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\hooks\pre-commit.sample
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\hooks\pre-merge-commit.sample
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\hooks\pre-push.sample
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\hooks\pre-rebase.sample
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\hooks\pre-receive.sample
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\hooks\prepare-commit-msg.sample
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\hooks\push-to-checkout.sample
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\hooks\sendemail-validate.sample
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\hooks\update.sample
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\info\exclude
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\logs\HEAD
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\logs\refs\heads\carolina-deliverable3
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\logs\refs\heads\main
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\logs\refs\remotes\origin\carolina-deliverable3
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\logs\refs\remotes\origin\main
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\01\0792be6e3bc096b1d942a3bbbbd83429787587
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\01\eec5c27611a58da3704980e8553f5afb1ad301
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\02\93ef843433376b3282078648836a8cbed5d7fb
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\07\bcbcd82c7196efeb270791acf0fc43c7d5ffa2
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\15\6ea1fcafc575e01b91adec5accdcf91c2df36a
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\19\62b7688b89167c67771810aea02bebd012d088
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\1a\f8d6a125313dba7d21e5b6063170b07fdc865d
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\1c\f10dc03ccb151bf13ebe4394b56f655b7ca427
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\1f\552a1cdc954cb06ccadd8edd8055c5aa989b0e
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\20\245e54bbc14245f4291e16e9da94a614b464da
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\27\cda3ec3973d9cf2d631da05187cf26aaf4824d
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\28\df47efb731131d4d36a5ea5df0cedb0ade7fed
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\2a\37dfa1074280385749bf6e0b5f585f2b62fb6d
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\2a\66d74f30a5db39418ac191947de77095adcd23
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\2d\df9e2d6ce5b8e6fa7a9d26b0a263db8d860940
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\30\d22bdd5c81343171b9eedd85a6918a2e41dd70
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\31\040fc7e9c3b7a74eb287f89760dc3d2a868a4e
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\32\74ce825a44fd263a284ccdb3d2056d26585120
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\34\350b343aa4452e15c596a8346a0d4836734958
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\36\3dd8cf5545553aed4b07a148bf5fd50ed3f2b7
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\37\28ed5a9535bbe787ef1b3efceea90e55852044
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\38\54d51165b6db34561908db092c7c1c21ba6df2
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\39\2f68d5d4920af217c6a2ff6ced1998f4c716bd
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\3b\9094f31b430900bb818fc1b9dcdbb9e357f21a
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\3c\924cc573f19af680ac33cc4890e55cb989eea2
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\3d\f60bc162862f7564ff886b53abeef759995a19
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\3e\0eb11134326761ce1919ecb4fe90e856a86375
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\40\8f12763228c5c10642f0c1a47237afc12f1ecb
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\42\60ad3d2891801a84ec39977a69a650b8601029
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\43\5e63bfc597e20b1d32a4e1243ab5e2c694a0cd
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\46\6f96be5957c85f63a4f6221e557608b99545df
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\48\93beac2288f5f30dc5a3666422ec2cdba821bc
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\4a\ef2c6534018af074fe7335b98567d3c0831593
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\56\b96b2fab7eb66e6686beb33d20850ed6d8a157
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\59\442b8c608d0c58f3c9145a269bb098ac235cf1
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\5c\18c9ee6b19e6a6e0156cd860f34c38ca801838
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\5e\8e6b47f700b21d4f9c932bc1745431cf563bbb
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\64\2219b8a1bbfb59fe65203eec4f8ab710140923
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\68\96224dc27412828a04b4857d1596e47b351ba7
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\69\5ad582179c28eee9b163ae71d48ac3632d49cd
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\6a\7cf7a2259d7abc346b61826d845b8f8959526f
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\6b\27cd53ef881e5cee73d48664e9683462e8abb6
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\6e\ad41b856645c61a19eec628d991bd9fb29ba77
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\78\75f353705119cbe77f201b646be68f8ee20af3
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\79\75f2baecde48d1e31de6efe074342ee20090b6
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\79\cf469935f01f9b253bc1db64b54951a0c9af3f
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\7a\054942f98be88ac013624fb66a50dd6c23cf40
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\7a\2ce9b46e3f1eb62005df7b267024376d1ca3a9
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\7e\8b50002b9dda135947df06778abd6dac4bfed1
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\7f\b97ba4f7c369dd9840f2e4dc21c44528a54f9b
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\83\972fadc2724842e111d0d3e2829a59ae3d3f45
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\83\d9afe01a3f2344e918778ab490dc68baba61e1
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\84\2ce73919c2417694ae056a84d4cb3725f03a79
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\84\3c7f039d494461ed84cd28f054c7589af1e1a0
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\85\1af3b8183d6e36c296a2b51cc36ddf819098e9
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\86\a5b191ebdd552ca27062860a15ff44ca09097f
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\8b\6793c065a6e982716e3bd8916eca5a6f6f0c81
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\8f\f0f036bec9a00266e7024d7436e6456b77e51d
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\90\a65bbd69d81770be10cb450fc665e2ee416be9
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\93\86004345b2b9f9ba2f17ebfc0bf14e78a99d6b
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\95\d4ae2bb4dd868be6cc3c5f31765623091c5ab9
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\95\f22172d8f93ee2c322bc0fba08fa2325a41620
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\9c\5f9f7437430106c725d435ceaeab5e5020597b
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\9e\2a29ec4fb0ce72d63e5a7599594d2287fb483b
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\9f\207f49813a2ca9fb300c34206ff0617ad145ed
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\a0\eb14949b42bddde9a1b2160efb728658a0dedd
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\a3\f34ee6d87521d7bb817a4a7647a88d31d8cc08
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\a6\a193fbe4bcb5e367d4075d321fd240ba7de209
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\aa\318b9ff52a9bc6b720bbe5ddf51d6518d92bb3
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\aa\5812432710c62184801fc606e364dc932fb188
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\aa\7d8bbe06f9c272f94a85899b3e03bfe06b9921
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\ab\5b97b6cf6251f4caaea52447ef790d1b7017a1
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\ac\851a9799c1ae989ff3116daa97d4ec20617f09
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\ad\ff737b05e517a051bc883a14774a4731a9488d
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\b4\689b69a5e96b402636e7a7d71e618a3eac5a4f
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\bf\62a70c4e5cc1474d59e01e4dc6a365c6ceb7dc
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\c0\af64e45ac24c6e023582e596bd66e1d1410570
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\c2\cdbf7adf69b8df3c60ded60363dbb61016a7c4
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\c4\525cca07421c576e7a136d810b53622a4e4549
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\c8\3e5a6ef2f31aa6c07b06aadcec65825b1ab490
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\ca\f71af571d53bcc0d797e01b14bbf31ec190e43
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\d1\635b8cb443594901c7e5cd24e6cce775e8bebf
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\d1\e41e038b528d978bb3293ec1eec8367df40a38
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\d4\3afc7cb0e36640505179ad5b34c74552301bdb
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\d4\ba91454bdaf642ddbaa28f04a68e8a1be8ec40
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\d5\64d0bc3dd917926892c55e3706cc116d5b165e
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\d6\ec64b73b988903bf42841d9381ba8f8d0e2dcf
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\d8\010ed81426a03c6e55228bd3d2c365ac645f39
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\d8\9bdde1110ec95134ed658193b323b06e7a188d
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\df\58872775bc8a1140d3380bc0e66ff0e4666bcc
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\e2\a3dcc8dc4d17eb0a455c97ed5db1ee9bbf7cda
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\e2\dbb5422afffcb46727b6eb9403320c1ea80bdc
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\e2\dc0c3c6817d4bf9527902aebef450085692047
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\e4\3859ca1c96febd35c864aa48016fcf027608bc
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\e6\9de29bb2d1d6434b8b29ae775ad8c2e48c5391
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\ea\c868284091b3b8a52d6825d1a46aea07429949
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\ef\8bdfedd5eb035d40d8997b7c97d4b5f3c0a7f5
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\f1\b8e4de2b41ab23e142552053a50821fb85edc0
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\f2\13af1c72d2d562edfc0ffa5c73fe7ff492495d
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\f5\708609311f65ccca7dc2af2622eec49c51bb9a
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\fa\dfadd521ea60841d2792abadd3584b9fa1be5d
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\fb\d3151ffc09ab8253acc6754eb8527dc59b6bd3
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\fc\261a879b1a2daf392f4f10b256b7f97a5718b4
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\fc\78395113da94d10c7ee87a1badf4a3aad9fd43
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\ff\5dee8952eeed0367c901ac4b5203a439722d7a
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\pack\pack-e1389c84f16866a942e77c9e0d2d7e2333a41467.idx
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\pack\pack-e1389c84f16866a942e77c9e0d2d7e2333a41467.pack
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\objects\pack\pack-e1389c84f16866a942e77c9e0d2d7e2333a41467.rev
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\refs\heads\carolina-deliverable3
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\refs\heads\main
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\refs\remotes\origin\carolina-deliverable3
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\.git\refs\remotes\origin\main
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\analysis\.gitkeep
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\analysis\Deliverable_3_ImprovedCode.py
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\analysis\Deliverable_3_OriginalCode.py
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\data\.gitkeep
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\data\Christchurch_merged_listings_2025_2026.csv
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\data\listings (1).csv
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\data\listings_03082025.csv
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\data\listings_03_08_2025.csv
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\data\listings_05102025.csv
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\data\listings_05_10_2025.csv
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\data\listings_06092025.csv
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\data\listings_06_09_2025.csv
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\data\listings_07112025.csv
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\data\listings_07_11_2025.csv
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\data\listings_11122025.csv
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\data\listings_11_12_2025.csv
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\data\listings_13022026.csv
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\data\listings_13_02_2026.csv
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\data\listings_16012026.csv
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\data\listings_16042026.csv
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\data\listings_16_01_2026.csv
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\data\listings_16_04_2026.csv
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\data\listings_17032026.csv
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\data\listings_17_03_2026.csv
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\data\listings_19062026.csv
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\data\listings_19_06_2026.csv
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\data\listings_20_06_2026.csv
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\data\listings_23052026.csv
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\data\listings_23_05_2026.csv
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\output\.gitkeep
C:\DATA422\Group Project\Listings_dataset_Oct25_June26\output\summary_statistics.txt
C:\DATA422\Group Project\New-Zealand-Tenancy-Data-Wrangling\.gitignore
C:\DATA422\Group Project\New-Zealand-Tenancy-Data-Wrangling\hello_jay.txt
C:\DATA422\Group Project\New-Zealand-Tenancy-Data-Wrangling\README.md
C:\DATA422\Group Project\New-Zealand-Tenancy-Data-Wrangling\.git\COMMIT_EDITMSG
C:\DATA422\Group Project\New-Zealand-Tenancy-Data-Wrangling\.git\config
C:\DATA422\Group Project\New-Zealand-Tenancy-Data-Wrangling\.git\description
C:\DATA422\Group Project\New-Zealand-Tenancy-Data-Wrangling\.git\FETCH_HEAD
C:\DATA422\Group Project\New-Zealand-Tenancy-Data-Wrangling\.git\HEAD
C:\DATA422\Group Project\New-Zealand-Tenancy-Data-Wrangling\.git\index
C:\DATA422\Group Project\New-Zealand-Tenancy-Data-Wrangling\.git\ORIG_HEAD
C:\DATA422\Group Project\New-Zealand-Tenancy-Data-Wrangling\.git\packed-refs
C:\DATA422\Group Project\New-Zealand-Tenancy-Data-Wrangling\.git\hooks\applypatch-msg.sample
C:\DATA422\Group Project\New-Zealand-Tenancy-Data-Wrangling\.git\hooks\commit-msg.sample
C:\DATA422\Group Project\New-Zealand-Tenancy-Data-Wrangling\.git\hooks\fsmonitor-watchman.sample
C:\DATA422\Group Project\New-Zealand-Tenancy-Data-Wrangling\.git\hooks\post-update.sample
C:\DATA422\Group Project\New-Zealand-Tenancy-Data-Wrangling\.git\hooks\pre-applypatch.sample
C:\DATA422\Group Project\New-Zealand-Tenancy-Data-Wrangling\.git\hooks\pre-commit.sample
C:\DATA422\Group Project\New-Zealand-Tenancy-Data-Wrangling\.git\hooks\pre-merge-commit.sample
C:\DATA422\Group Project\New-Zealand-Tenancy-Data-Wrangling\.git\hooks\pre-push.sample
C:\DATA422\Group Project\New-Zealand-Tenancy-Data-Wrangling\.git\hooks\pre-rebase.sample
C:\DATA422\Group Project\New-Zealand-Tenancy-Data-Wrangling\.git\hooks\pre-receive.sample
C:\DATA422\Group Project\New-Zealand-Tenancy-Data-Wrangling\.git\hooks\prepare-commit-msg.sample
C:\DATA422\Group Project\New-Zealand-Tenancy-Data-Wrangling\.git\hooks\push-to-checkout.sample
C:\DATA422\Group Project\New-Zealand-Tenancy-Data-Wrangling\.git\hooks\sendemail-validate.sample
C:\DATA422\Group Project\New-Zealand-Tenancy-Data-Wrangling\.git\hooks\update.sample
C:\DATA422\Group Project\New-Zealand-Tenancy-Data-Wrangling\.git\info\exclude
C:\DATA422\Group Project\New-Zealand-Tenancy-Data-Wrangling\.git\logs\HEAD
C:\DATA422\Group Project\New-Zealand-Tenancy-Data-Wrangling\.git\logs\refs\heads\carolina
C:\DATA422\Group Project\New-Zealand-Tenancy-Data-Wrangling\.git\logs\refs\heads\carolina-deliverable-5
C:\DATA422\Group Project\New-Zealand-Tenancy-Data-Wrangling\.git\logs\refs\heads\jayant
C:\DATA422\Group Project\New-Zealand-Tenancy-Data-Wrangling\.git\logs\refs\heads\main

In [24]:
!dir

 Volume in drive C is Windows
 Volume Serial Number is 560B-9C39

 Directory of C:\DATA422\Group Project\New-Zealand-Tenancy-Data-Wrangling

29/07/2026  01:14 am    <DIR>          .
09/09/2026  07:57 pm    <DIR>          ..
29/07/2026  12:18 am             4,846 .gitignore
29/07/2026  01:13 am                80 hello_jay.txt
29/07/2026  12:18 am                78 README.md
               3 File(s)          5,004 bytes
               2 Dir(s)  253,227,089,920 bytes free

In [25]:
%cd "C:\DATA422\Group Project\Listings_dataset_Oct25_June26"

C:\DATA422\Group Project\Listings_dataset_Oct25_June26

In [26]:
!git branch

* carolina-deliverable3
  main

In [27]:
!git checkout -b carolina-deliverable5

Switched to a new branch 'carolina-deliverable5'

In [28]:
!git checkout carolina-deliverable5

Already on 'carolina-deliverable5'

In [29]:
Listings_dataset_Oct25_June26/
└── analysis/
    ├── Deliverable_3_ImprovedCode.py
    ├── Deliverable_3_OriginalCode.py
    └── Deliverable_5.py

SyntaxError: invalid character '└' (U+2514) (2672633301.py, line 2)

In [30]:
%cd "C:\DATA422\Group Project\Listings_dataset_Oct25_June26"

C:\DATA422\Group Project\Listings_dataset_Oct25_June26

In [31]:
!git branch

  carolina-deliverable3
* carolina-deliverable5
  main

In [32]:
%cd "C:\DATA422\Group Project\Listings_dataset_Oct25_June26"
!git branch

C:\DATA422\Group Project\Listings_dataset_Oct25_June26
  carolina-deliverable3
* carolina-deliverable5
  main

In [33]:
!git status

On branch carolina-deliverable5
nothing to commit, working tree clean

In [34]:
!dir analysis

 Volume in drive C is Windows
 Volume Serial Number is 560B-9C39

 Directory of C:\DATA422\Group Project\Listings_dataset_Oct25_June26\analysis

13/10/2026  03:29 pm    <DIR>          .
13/10/2026  03:41 pm    <DIR>          ..
13/10/2026  03:28 pm                 0 .gitkeep
13/10/2026  03:29 pm             8,206 Deliverable_3_ImprovedCode.py
13/10/2026  03:29 pm            12,280 Deliverable_3_OriginalCode.py
               3 File(s)         20,486 bytes
               2 Dir(s)  253,236,867,072 bytes free

In [35]:
!dir

 Volume in drive C is Windows
 Volume Serial Number is 560B-9C39

 Directory of C:\DATA422\Group Project\Listings_dataset_Oct25_June26

13/10/2026  03:41 pm    <DIR>          .
09/09/2026  07:57 pm    <DIR>          ..
12/08/2026  05:53 pm             4,846 .gitignore
13/10/2026  03:29 pm    <DIR>          analysis
13/10/2026  03:29 pm    <DIR>          data
13/10/2026  03:30 pm    <DIR>          output
13/10/2026  09:50 am             2,101 README.md
               2 File(s)          6,947 bytes
               5 Dir(s)  253,236,793,344 bytes free

In [1]:
!dir

 Volume in drive C is Windows
 Volume Serial Number is 560B-9C39

 Directory of C:\Users\CFakaosi

18/10/2026  07:39 pm    <DIR>          .
12/05/2026  10:30 pm    <DIR>          ..
27/03/2026  10:36 am    <DIR>          .anaconda
29/07/2026  12:31 am               207 .bash_history
08/06/2026  01:16 pm    <DIR>          .cache
27/03/2026  10:37 am    <DIR>          .conda
16/05/2026  12:21 pm                70 .condarc
10/08/2026  04:38 pm    <DIR>          .copilot
12/08/2026  05:50 pm               165 .gitconfig
18/10/2026  07:39 pm    <DIR>          .ipynb_checkpoints
20/04/2026  10:46 pm    <DIR>          .ipython
12/05/2026  11:47 am    <DIR>          .jupyter
13/10/2026  03:31 pm                26 .lesshst
22/04/2026  10:44 pm    <DIR>          .matplotlib
23/07/2025  11:43 am    <DIR>          .ms-ad
10/08/2026  01:57 pm               469 .python_history
04/06/2026  09:34 pm    <DIR>          .satscan
27/07/2026  10:30 pm    <DIR>          .vscode
27/07/2026  10:30 pm    <DIR>          .vscode-shared
17/05/2026  05:26 pm         1,263,754 33058094_CarolinaFakaosi_Assignment2.ipynb
06/06/2026  06:49 pm            15,563 Cases.cas
21/09/2026  02:43 pm         7,196,117 christchurch_airbnb_with_sa2.csv
02/04/2026  08:00 am    <DIR>          Contacts
06/06/2026  05:23 pm            46,688 Controls.ctl
06/06/2026  05:52 pm            83,878 Coordinates(2).geo
06/06/2026  06:52 pm            69,059 Coordinates.geo
17/02/2026  02:05 pm    <DIR>          Data Improvement AGOL
21/09/2026  12:52 pm    <DIR>          Data Wrangling
18/10/2026  07:39 pm         1,512,621 Deliverable 5.ipynb
18/10/2026  07:39 pm         1,512,621 Deliverable_5.ipynb
01/12/2025  10:20 am    <DIR>          Director
28/07/2026  09:46 am    <DIR>          Documents
16/10/2026  01:14 pm    <DIR>          Downloads
25/09/2026  11:50 am    <DIR>          DVR
23/06/2026  09:41 am               613 DVR.ipynb
07/06/2026  03:32 pm                56 Eneio_Beach_Tonga.csv
02/04/2026  08:00 am    <DIR>          Favorites
08/06/2026  02:06 am         1,255,590 Frankton-Suburb-LDS-GPKG.zip
08/06/2026  02:08 am           696,320 Frankton_suburb.gpkg
15/06/2026  09:11 am           178,573 Hamilton_map.ipynb
21/05/2026  01:11 am    <DIR>          Lab 2
17/10/2026  02:09 pm    <DIR>          Land Information New Zealand
02/04/2026  08:00 am    <DIR>          Links
20/09/2026  10:50 pm           561,027 listings_05_10_2025.csv
20/09/2026  10:50 pm           572,581 listings_07_11_2025.csv
20/09/2026  10:50 pm           583,922 listings_11_12_2025.csv
20/09/2026  10:50 pm           601,647 listings_13_02_2026.csv
20/09/2026  10:50 pm           576,262 listings_16_01_2026.csv
20/09/2026  10:50 pm           634,483 listings_16_04_2026.csv
20/09/2026  10:50 pm           625,135 listings_17_03_2026.csv
20/09/2026  10:50 pm           686,219 listings_19_06_2026.csv
20/09/2026  10:50 pm           651,583 listings_23_05_2026.csv
09/06/2026  01:58 pm                60 Mount_Eden.csv
15/06/2026  10:05 am           104,032 Mount_Eden.ipynb
15/06/2026  01:50 am                60 Mount_Eden_LatLong_net.csv
15/06/2026  01:47 am    <DIR>          Mt_Eden
02/04/2026  08:00 am    <DIR>          Music
23/06/2026  09:46 am       481,378,304 nz-properties-national-district-valuation-roll-restricted-ac.gpkg
15/06/2026  01:33 am           438,272 nz-property-titles-linz.gpkg
22/07/2025  04:39 pm    <DIR>          OneDrive
17/10/2026  02:09 pm    <DIR>          OneDrive - Land Information New Zealand
09/06/2026  07:52 pm           435,312 Pepeha.ipynb
08/06/2026  08:25 pm            34,381 Pepeha_Assignment2.ipynb
08/06/2026  07:27 pm    <DIR>          Pepeha_folder
06/06/2026  06:15 pm            86,739 Population(2).pop
06/06/2026  06:51 pm            37,787 Population.pop
23/09/2026  03:50 pm       218,072,302 sales_all.psv.gz
02/04/2026  08:00 am    <DIR>          Saved Games
02/04/2026  08:00 am    <DIR>          Searches
08/06/2026  05:56 pm           102,942 static_map.png
08/06/2026  02:07 am           696,320 suburb-locality.gpkg
15/06/2026  12:29 am        42,307,584 territorial-authority-2026-statsnz.gpkg
07/06/2026  05:55 pm             3,508 tonga_map.html
08/06/2026  05:53 pm             1,196 Tuanekivale.geojson
08/06/2026  05:53 pm            98,304 Tuanekivale.gpkg
08/06/2026  04:40 pm    <DIR>          Tuanekivale_poly
08/06/2026  04:40 pm               588 Tuanekivale_poly.shp
08/06/2026  04:07 pm               887 Tuanekivale_polygon.csv
15/06/2026  12:26 am    <DIR>          Untitled Folder
21/05/2026  01:09 am                72 Untitled.ipynb
21/05/2026  01:11 am                72 Untitled1.ipynb
02/06/2026  11:57 pm               617 Untitled2.ipynb
23/06/2026  09:39 am                72 Untitled3.ipynb
23/09/2026  03:51 pm               617 Untitled4.ipynb
29/07/2026  01:24 pm    <DIR>          venv
02/04/2026  08:00 am    <DIR>          Videos
              50 File(s)    763,125,277 bytes
              36 Dir(s)  253,233,668,096 bytes free

In [4]:
import os

os.path.exists(r"C:\Users\CFakaosi\Deliverable_5.ipynb")

True